import {test,expect} from '@playwright/test';

test('发送记录删除支持取消、失败重试和刷新保持，发送中记录禁用删除',async({page})=>{
  const base='http://127.0.0.1:3101/api/v1',sign=await page.request.post(base+'/auth/login',{headers:{'X-Forwarded-For':'127.0.0.44'},data:{username:'e2e-teacher',password:'test-only-password-123'}});expect(sign.ok()).toBeTruthy();
  const headers={'X-CSRF-Token':(await sign.json()).csrfToken,'X-Forwarded-For':'127.0.0.44'},groups=(await (await page.request.get(base+'/admin/qq/groups')).json()).items;
  const records:{id:string}[]=[];for(const title of ['删除测试甲','删除测试乙','发送中记录']){const response=await page.request.post(base+'/admin/notifications',{headers,data:{requestId:crypto.randomUUID(),title,content:'仅用于隔离删除流程测试。',groupIds:[groups[0].id]}});expect(response.status()).toBe(202);records.push(await response.json());}
  const botHeaders={Authorization:'Bearer e2e-service-token'},targets=(await (await page.request.post(base+'/internal/qq/notifications/claim',{headers:botHeaders,data:{limit:20}})).json()).items;
  for(const target of targets.filter((t:any)=>[records[0].id,records[1].id].includes(t.notificationId))){await page.request.post(base+'/internal/qq/notifications/'+target.id+'/begin',{headers:botHeaders,data:{claimToken:target.claimToken}});await page.request.post(base+'/internal/qq/notifications/'+target.id+'/result',{headers:botHeaders,data:{claimToken:target.claimToken,status:target.notificationId===records[0].id?'sent':'failed',messageId:'isolated-receipt',errorCode:'测试失败'}});}
  await page.goto('/admin/notifications');
  const first=page.getByRole('article').filter({hasText:'删除测试甲'}),second=page.getByRole('article').filter({hasText:'删除测试乙'}),pending=page.getByRole('article').filter({hasText:'发送中记录'}),dialog=page.getByRole('dialog',{name:'删除发送记录'});
  await expect(pending.getByRole('button',{name:'删除记录'})).toBeDisabled();await first.getByRole('button',{name:'删除记录'}).click();await expect(dialog).toContainText('不会撤回 QQ 群中已发送的消息');await dialog.getByRole('button',{name:'取消',exact:true}).click();await expect(first).toBeVisible();await expect(dialog).not.toBeVisible();
  await first.getByRole('button',{name:'删除记录'}).click();await dialog.getByRole('button',{name:'确认删除'}).click();await expect(first).toHaveCount(0);await expect(second).toBeVisible();
  const path='**/api/v1/admin/notifications/'+records[1].id;await page.route(path,route=>route.fulfill({status:503,json:{error:{code:'TEST_ERROR',message:'暂时无法删除，请重试。'}}}));await second.getByRole('button',{name:'删除记录'}).click();await dialog.getByRole('button',{name:'确认删除'}).click();await expect(dialog).toContainText('暂时无法删除，请重试。');const remaining=(await (await page.request.get(base+'/admin/notifications')).json()).items;expect(remaining.some((item:any)=>item.id===records[1].id)).toBeTruthy();await page.screenshot({path:'qa/screenshots/delete-notification-dialog.png',fullPage:true});
  await page.unroute(path);await dialog.getByRole('button',{name:'确认删除'}).click();await expect(second).toHaveCount(0);await page.reload();await expect(page.getByRole('heading',{name:'一键发送通知'})).toBeVisible();await expect(first).toHaveCount(0);await expect(second).toHaveCount(0);await expect(pending).toBeVisible();
});
