import { mkdtempSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { spawn } from 'node:child_process';
import { createApp } from '../apps/api/src/app.js';
import { hashPassword } from '../apps/api/src/services/auth.js';
import type { BotController } from '../apps/api/src/services/bot-control.js';
const directory=mkdtempSync(join(tmpdir(),'campus-e2e-'));
let appId='',secret='',running=false;const botController:BotController={status:()=>({appId,appSecretConfigured:!!secret,processRunning:running}),save:input=>{appId=input.appId;if(input.appSecret)secret=input.appSecret;return botController.status();},start:async()=>{running=true;return {ok:true,message:'机器人已启动，正在连接 QQ 开放平台。',processRunning:true};},stop:()=>{running=false;return {ok:true,message:'机器人已停止。',processRunning:false};}};
const modelFetch:typeof fetch=async()=>new Response(JSON.stringify({choices:[{finish_reason:'stop',message:{content:JSON.stringify({faqId:'connection-check',match:'clear'})}}],usage:{prompt_tokens:100,completion_tokens:20}}),{headers:{'Content-Type':'application/json'}});
const {app,store,models}=await createApp({dataDir:join(directory,'data'),localDir:join(directory,'.local'),modelStateDir:join(directory,'models'),dbPath:join(directory,'campus.db'),port:3101,logger:false,modelKey:'',botToken:'e2e-service-token',developerKey:'test-developer-key-123',rateLimit:1000,loginRateLimit:1000,origins:['http://127.0.0.1:8180']},{botController,modelFetch});
store.seedDemo();store.setAdmin('e2e-teacher',await hashPassword('test-only-password-123'));
const first=store.registerQqGroup('e2e_group_openid_123456');store.syncQqGroup(first.id,'','2026级1班工作群');
const second=store.registerQqGroup('e2e_group_openid_654321');store.syncQqGroup(second.id,'','2026级2班工作群');
models.settings.saveKey('qwen','e2e-qwen-key');models.settings.saveKey('deepseek','e2e-deepseek-key');models.settings.saveKey('zhipu','e2e-zhipu-key');
await app.listen({host:'127.0.0.1',port:3101});
const web=spawn(process.execPath,['scripts/serve-web.mjs'],{stdio:'inherit',windowsHide:true,env:{...process.env,API_PORT:'3101',WEB_PORT:'8180',WEB_HOST:'127.0.0.1'}});
for(const signal of ['SIGINT','SIGTERM'] as const)process.on(signal,()=>{web.kill();void app.close();});
web.on('exit',()=>void app.close());
