import { createReadStream, existsSync, mkdirSync, readFileSync, rmSync } from 'node:fs';
import { extname, join } from 'node:path';
import type { FastifyInstance } from 'fastify';
import type { FaqInput, FaqLibraryType, MaterialStatus, RagEvaluationCase, RagSettings } from '@campus/contracts';
import { FAQ_INPUT_SCHEMA, FAQ_PATCH_SCHEMA, PAGE_QUERY_SCHEMA } from '@campus/contracts';
import type { Store, ListQuery } from '../../db/store.js';
import { AppError } from '../../errors.js';
import { API_PREFIX, ID_PARAMS_SCHEMA, type RouteContext } from '../../http/context.js';
import { createGuards } from '../../http/guards.js';
import { createExportPackage, createFileArchive, faqPackagePath, ragPackagePath } from '../../services/export-package.js';
import { createFaqWorkbook, parseFaqWorkbook } from '../../services/faq-workbook.js';
import { materialSourceKey } from '../../services/materials.js';
import { createRagWorkbook } from '../../services/rag-workbook.js';
import { attachmentKind, partBuffer, safeName, saveBuffer, saveFolderZip } from '../../services/uploads.js';

export function registerKnowledgeRoutes(app: FastifyInstance, context: RouteContext, phase:'internal'|'knowledge'|'materials'|'all'='all') {
  const {config,store,rag,materials,materialDirectory,answerOptimizer}=context,{bot,admin,adminWrite}=createGuards(context),prefix=API_PREFIX;

  if(phase==='internal'||phase==='all') {
  app.post(prefix+'/internal/qq/materials',{bodyLimit:27*1024*1024,preHandler:bot,config:{rateLimit:{max:120,timeWindow:'1 minute'}},schema:{hide:true}},async(req,reply)=>{let metadataText='',file:{buffer:Buffer;mime:string;name:string}|null=null;for await(const part of req.parts()){if(part.type==='field'){if(part.fieldname==='metadata')metadataText=String(part.value);continue;}if(part.fieldname!=='file'||file)throw new AppError(400,'MATERIAL_FILE_LIMIT','每次只能接收一个资料文件。');file={buffer:await partBuffer(part,25*1024*1024),mime:part.mimetype||'application/octet-stream',name:safeName(part.filename)};}if(!file)throw new AppError(400,'EMPTY_UPLOAD','没有收到资料文件。');let metadata:{messageId:string;senderId:string;senderName?:string};try{metadata=JSON.parse(metadataText);}catch{throw new AppError(400,'INVALID_MATERIAL_METADATA','资料来源信息无效。');}if(typeof metadata.messageId!=='string'||!metadata.messageId||metadata.messageId.length>200||/[\p{Cc}\p{Cf}]/u.test(metadata.messageId)||!/^[A-Za-z0-9_-]{1,160}$/.test(metadata.senderId)||metadata.senderName&&metadata.senderName.length>80)throw new AppError(400,'INVALID_MATERIAL_METADATA','资料来源信息无效。');const extension=extname(file.name).toLowerCase(),allowed=new Set(['.pdf','.doc','.docx','.xls','.xlsx','.ppt','.pptx','.txt','.csv','.zip','.rar','.7z']);if(!allowed.has(extension))throw new AppError(400,'UNSUPPORTED_MATERIAL','资料仅支持 PPT、PDF、Word、Excel 及常用文档压缩包。');const sourceKey=materialSourceKey(metadata.messageId,file.name,file.buffer.length),existing=store.materialBySourceKey(sourceKey);if(existing){reply.code(200);return existing;}const categoryId=await materials.classify(file.name,store.listMaterialCategories()),storedName=saveBuffer(materialDirectory,file.buffer,extension.slice(1));try{const item=store.createMaterialItem({sourceKey,categoryId,name:file.name,storedName,mime:file.mime,size:file.buffer.length,senderId:metadata.senderId,senderName:metadata.senderName});reply.code(201);return item;}catch(error){rmSync(join(materialDirectory,storedName),{force:true});throw error;}});
  app.get<{Params:{id:string}}>(prefix+'/internal/qq/attachments/:id',{preHandler:bot,schema:{hide:true,params:ID_PARAMS_SCHEMA}},async(req,reply)=>{const faqFile=store.attachmentFile(req.params.id),ragFile=faqFile?undefined:store.ragFile(req.params.id),notificationFile=faqFile||ragFile?undefined:store.notificationAttachmentFile(req.params.id),file=faqFile||ragFile||notificationFile;if(!file)throw new AppError(404,'NOT_FOUND','附件不存在。');const path=faqFile?join(config.dataDir,'faq-attachments',faqFile.faq_id,faqFile.stored_name):ragFile?join(rag.directory,ragFile.stored_name):join(config.dataDir,'notification-attachments',notificationFile!.stored_name);reply.header('Content-Type',file.mime).header('Content-Length',String(file.size)).header('Content-Disposition',`attachment; filename*=UTF-8''${encodeURIComponent(file.name)}`);return reply.send(createReadStream(path));});
  }
  if(phase==='knowledge'||phase==='all') {
  app.get<{Querystring:ListQuery}>(prefix+'/faqs',{preHandler:admin,schema:{tags:['FAQ'],querystring:PAGE_QUERY_SCHEMA}},async req=>store.listFaqs(req.query));
  app.post<{Body:FaqInput}>(prefix+'/faqs',{preHandler:adminWrite,schema:{tags:['FAQ'],body:FAQ_INPUT_SCHEMA}},async(req,reply)=>{const result=store.saveFaq(req.body,req.campusSession!.user.id);reply.code(201);return result;});
  app.post<{Body:{ids:string[];libraryType:FaqLibraryType;action:'update'|'delete';category?:string;status?:'active'|'disabled'}}>(prefix+'/faqs/batch',{preHandler:adminWrite,schema:{tags:['FAQ'],body:{type:'object',additionalProperties:false,required:['ids','libraryType','action'],properties:{ids:{type:'array',minItems:1,maxItems:100,uniqueItems:true,items:{type:'string',minLength:8,maxLength:100}},libraryType:{enum:['answer','forbidden']},action:{enum:['update','delete']},category:{type:'string',minLength:1,maxLength:40},status:{enum:['active','disabled']}}}}},async req=>{const result=store.batchFaqs(req.body.ids,req.body.libraryType,req.body.action,req.campusSession!.user.id,{category:req.body.category,status:req.body.status});if(req.body.action==='delete')for(const id of result.deletedIds)rmSync(join(config.dataDir,'faq-attachments',id),{recursive:true,force:true});return result;});
  app.post(prefix+'/faqs/abuse-lexicon/import',{preHandler:adminWrite,schema:{tags:['FAQ']}},async req=>store.importAbuseLexicon(req.campusSession!.user.id));
  app.post<{Body:{question:string;answer:string}}>(prefix+'/faqs/optimize-answer',{preHandler:adminWrite,config:{rateLimit:{max:20,timeWindow:'1 minute'}},schema:{tags:['FAQ'],body:{type:'object',additionalProperties:false,required:['question','answer'],properties:{question:{type:'string',maxLength:200},answer:{type:'string',minLength:1,maxLength:1500}}}}},async req=>answerOptimizer.optimize(req.body.question,req.body.answer));
  app.patch<{Params:{id:string};Body:FaqInput&{version:number}}>(prefix+'/faqs/:id',{preHandler:adminWrite,schema:{tags:['FAQ'],params:ID_PARAMS_SCHEMA,body:FAQ_PATCH_SCHEMA}},async req=>store.saveFaq(req.body,req.campusSession!.user.id,req.params.id,req.body.version));
  app.delete<{Params:{id:string};Body:{version:number}}>(prefix+'/faqs/:id',{preHandler:adminWrite,schema:{tags:['FAQ'],params:ID_PARAMS_SCHEMA,body:{type:'object',additionalProperties:false,required:['version'],properties:{version:{type:'integer',minimum:1}}}}},async req=>{const deleted=store.deleteFaq(req.params.id,req.campusSession!.user.id,req.body.version);rmSync(join(config.dataDir,'faq-attachments',deleted.id),{recursive:true,force:true});return {ok:true,id:deleted.id};});
  app.get<{Querystring:{libraryType?:FaqLibraryType}}>(prefix+'/faqs/export',{preHandler:admin,schema:{tags:['FAQ'],querystring:{type:'object',additionalProperties:false,properties:{libraryType:{enum:['answer','forbidden']}}}}},async req=>({version:1,exportedAt:Date.now(),libraryType:req.query.libraryType||'answer',items:store.listFaqs({libraryType:req.query.libraryType||'answer',pageSize:100}).items.map(({attachments:_,...faq})=>faq)}));
  app.post<{Body:{items:(FaqInput&{id?:string})[]}}>(prefix+'/faqs/import',{preHandler:adminWrite,schema:{tags:['FAQ'],body:{type:'object',additionalProperties:false,required:['items'],properties:{items:{type:'array',minItems:1,maxItems:1000,items:{...FAQ_INPUT_SCHEMA,properties:{...FAQ_INPUT_SCHEMA.properties,id:{type:'string',maxLength:100}}}}}}}},async(req,reply)=>{const items=store.importFaqs(req.body.items,req.campusSession!.user.id);reply.code(201);return {count:items.length,items};});
  app.get<{Querystring:{libraryType?:FaqLibraryType}}>(prefix+'/faqs/export.xlsx',{preHandler:admin,schema:{tags:['FAQ'],querystring:{type:'object',additionalProperties:false,properties:{libraryType:{enum:['answer','forbidden']}}}}},async(req,reply)=>{const libraryType=req.query.libraryType||'answer',items=store.listFaqsForExport(libraryType),{buffer,mime}=await createFaqWorkbook(items,libraryType),name=`${libraryType==='answer'?'答疑题库':'敏感词库'}-${new Date().toISOString().slice(0,10)}.xlsx`;reply.header('Content-Type',mime).header('Content-Disposition',`attachment; filename*=UTF-8''${encodeURIComponent(name)}`).header('Cache-Control','no-store');return reply.send(buffer);});
  app.get<{Querystring:{libraryType?:FaqLibraryType}}>(prefix+'/faqs/export-package.zip',{preHandler:admin,schema:{tags:['FAQ'],querystring:{type:'object',additionalProperties:false,properties:{libraryType:{enum:['answer','forbidden']}}}}},async(req,reply)=>{
    const libraryType=req.query.libraryType||'answer',items=store.listFaqs({libraryType,pageSize:10000}).items,packageFiles:{sourcePath:string;packagePath:string}[]=[],attachments=libraryType==='answer'?items.flatMap((item,itemIndex)=>(item.attachments||[]).map((meta,attachmentIndex)=>{const file=store.attachmentFile(meta.id);if(!file)throw new AppError(404,'ATTACHMENT_MISSING',`附件“${meta.name}”不存在。`);const sourcePath=join(config.dataDir,'faq-attachments',file.faq_id,file.stored_name);if(!existsSync(sourcePath))throw new AppError(404,'ATTACHMENT_MISSING',`附件“${meta.name}”的真实文件不存在。`);const packagePath=faqPackagePath(itemIndex+1,item.question,attachmentIndex+1,file.name);packageFiles.push({sourcePath,packagePath});return {faqId:item.id,name:file.name,kind:file.kind,mime:file.mime,content:Buffer.alloc(0),packagePath};})):[];
    const title=libraryType==='answer'?'答疑题库':'敏感词库',{buffer}=await createFaqWorkbook(items,libraryType,attachments,{embedAttachments:false,includePackageLinks:true}),date=new Date().toISOString().slice(0,10),name=`${title}完整资料包-${date}.zip`,archive=createExportPackage(`${title}清单-${date}.xlsx`,buffer,packageFiles);reply.header('Content-Type','application/zip').header('Content-Disposition',`attachment; filename*=UTF-8''${encodeURIComponent(name)}`);return reply.send(archive);
  });
  app.post<{Querystring:{libraryType?:FaqLibraryType}}>(prefix+'/faqs/import.xlsx',{bodyLimit:55*1024*1024,preHandler:adminWrite,schema:{tags:['FAQ'],querystring:{type:'object',additionalProperties:false,properties:{libraryType:{enum:['answer','forbidden']}}}}},async(req,reply)=>{const libraryType=req.query.libraryType||'answer',items:FaqInput[]=[];let count=0,total=0;for await(const part of req.parts()){if(part.type!=='file')continue;if(extname(part.filename).toLowerCase()!=='.xlsx')throw new AppError(400,'INVALID_XLSX','请选择系统导出的 .xlsx 固定模板。');const buffer=await partBuffer(part,10*1024*1024);total+=buffer.length;if(++count>20||total>50*1024*1024)throw new AppError(413,'XLSX_LIMIT','每次最多导入 20 个、合计 50 MB 的 Excel 文件。');items.push(...await parseFaqWorkbook(buffer,libraryType));}if(!items.length)throw new AppError(400,'INVALID_XLSX','请选择系统导出的 .xlsx 固定模板。');const saved=store.transaction(()=>{const known=new Set(store.listCategories(libraryType).map(x=>x.name));for(const item of items){if(!known.has(item.category)){store.createCategory(item.category,libraryType);known.add(item.category);}}return store.importFaqs(items,req.campusSession!.user.id);});reply.code(201);return {count:saved.length};});
  app.get<{Querystring:{libraryType:FaqLibraryType}}>(prefix+'/knowledge/categories',{preHandler:admin,schema:{tags:['知识库'],querystring:{type:'object',additionalProperties:false,required:['libraryType'],properties:{libraryType:{enum:['answer','forbidden']}}}}},async req=>({items:store.listCategories(req.query.libraryType)}));
  app.post<{Body:{name:string;libraryType:FaqLibraryType}}>(prefix+'/knowledge/categories',{preHandler:adminWrite,schema:{tags:['知识库'],body:{type:'object',additionalProperties:false,required:['name','libraryType'],properties:{name:{type:'string',minLength:1,maxLength:40},libraryType:{enum:['answer','forbidden']}}}}},async(req,reply)=>{const result=store.createCategory(req.body.name,req.body.libraryType);reply.code(201);return result;});
  app.patch<{Params:{id:string};Body:{name:string}}>(prefix+'/knowledge/categories/:id',{preHandler:adminWrite,schema:{tags:['知识库'],params:ID_PARAMS_SCHEMA,body:{type:'object',additionalProperties:false,required:['name'],properties:{name:{type:'string',minLength:1,maxLength:40}}}}},async req=>store.renameCategory(req.params.id,req.body.name));
  app.delete<{Params:{id:string}}>(prefix+'/knowledge/categories/:id',{preHandler:adminWrite,schema:{tags:['知识库'],params:ID_PARAMS_SCHEMA}},async req=>store.deleteCategory(req.params.id));
  app.post<{Params:{id:string};Querystring:{kind?:'folder';folderName?:string}}>(prefix+'/faqs/:id/attachments',{bodyLimit:70*1024*1024,preHandler:adminWrite,schema:{tags:['FAQ 附件'],params:ID_PARAMS_SCHEMA,querystring:{type:'object',additionalProperties:false,properties:{kind:{enum:['folder']},folderName:{type:'string',maxLength:100}}}}},async(req,reply)=>{const faq=store.getFaq(req.params.id);if(!faq)throw new AppError(404,'NOT_FOUND','知识条目不存在。');const existing=store.listFaqAttachments(faq.id),files:{name:string;mime:string;buffer:Buffer}[]=[];let total=0;for await(const part of req.parts()){if(part.type!=='file')continue;const buffer=await partBuffer(part);total+=buffer.length;if(total>60*1024*1024)throw new AppError(413,'FILE_TOO_LARGE','一次上传不能超过 60 MB。');files.push({name:safeName(part.filename),mime:part.mimetype,buffer});}if(!files.length)throw new AppError(400,'EMPTY_UPLOAD','请选择要上传的文件。');const incoming=req.query.kind==='folder'?1:files.length;if(existing.length+incoming>10)throw new AppError(409,'ATTACHMENT_LIMIT','每个答案最多保存 10 个附件。');const dir=join(config.dataDir,'faq-attachments',faq.id);mkdirSync(dir,{recursive:true});if(req.query.kind==='folder'){const saved=await saveFolderZip(dir,files);const item=store.addFaqAttachment(faq.id,{name:`${safeName(req.query.folderName||files[0].name.split('/')[0]||'资料文件夹')}.zip`,storedName:saved.stored,kind:'folder',mime:'application/zip',size:saved.size});reply.code(201);return {count:1,items:[item]};}const items=[] as ReturnType<Store['addFaqAttachment']>[];for(const file of files){const kind=attachmentKind(file.name,file.mime),stored=saveBuffer(dir,file.buffer,extname(file.name).slice(1));items.push(store.addFaqAttachment(faq.id,{name:safeName(file.name),storedName:stored,kind,mime:file.mime||'application/octet-stream',size:file.buffer.length}));}reply.code(201);return {count:items.length,items};});
  app.delete<{Params:{id:string;attachmentId:string}}>(prefix+'/faqs/:id/attachments/:attachmentId',{preHandler:adminWrite,schema:{tags:['FAQ 附件'],params:{type:'object',additionalProperties:false,required:['id','attachmentId'],properties:{id:{type:'string'},attachmentId:{type:'string'}}}}},async req=>{const file=store.attachmentFile(req.params.attachmentId);if(!file||file.faq_id!==req.params.id)throw new AppError(404,'NOT_FOUND','附件不存在。');store.deleteFaqAttachment(file.id);rmSync(join(config.dataDir,'faq-attachments',file.faq_id,file.stored_name),{force:true});return {ok:true};});
  app.get<{Params:{id:string;attachmentId:string}}>(prefix+'/faqs/:id/attachments/:attachmentId/download',{preHandler:admin,schema:{tags:['FAQ 附件'],params:{type:'object',additionalProperties:false,required:['id','attachmentId'],properties:{id:{type:'string'},attachmentId:{type:'string'}}}}},async(req,reply)=>{const file=store.attachmentFile(req.params.attachmentId);if(!file||file.faq_id!==req.params.id)throw new AppError(404,'NOT_FOUND','附件不存在。');reply.header('Content-Type',file.mime).header('Content-Disposition',`attachment; filename*=UTF-8''${encodeURIComponent(file.name)}`);return reply.send(createReadStream(join(config.dataDir,'faq-attachments',file.faq_id,file.stored_name)));});
  app.get(prefix+'/rag/tree',{preHandler:admin,schema:{tags:['知识库技能']}},async()=>({folders:store.listRagFolders(),documents:store.listRagDocuments()}));
  app.post<{Body:{name:string;parentId?:string|null}}>(prefix+'/rag/folders',{preHandler:adminWrite,schema:{tags:['知识库技能'],body:{type:'object',additionalProperties:false,required:['name'],properties:{name:{type:'string',minLength:1,maxLength:80},parentId:{anyOf:[{type:'string'},{type:'null'}]}}}}},async(req,reply)=>{const result=store.saveRagFolder(req.body.name,req.body.parentId||null);reply.code(201);return result;});
  app.patch<{Params:{id:string};Body:{name:string}}>(prefix+'/rag/folders/:id',{preHandler:adminWrite,schema:{tags:['知识库技能'],params:ID_PARAMS_SCHEMA,body:{type:'object',additionalProperties:false,required:['name'],properties:{name:{type:'string',minLength:1,maxLength:80}}}}},async req=>store.renameRagFolder(req.params.id,req.body.name));
  app.delete<{Params:{id:string}}>(prefix+'/rag/folders/:id',{preHandler:adminWrite,schema:{tags:['知识库技能'],params:ID_PARAMS_SCHEMA}},async req=>store.deleteRagFolder(req.params.id));
  app.post<{Querystring:{folderId?:string}}>(prefix+'/rag/documents',{bodyLimit:210*1024*1024,preHandler:adminWrite,schema:{tags:['知识库技能'],querystring:{type:'object',additionalProperties:false,properties:{folderId:{type:'string',maxLength:100}}}}},async(req,reply)=>{const documents=[];let total=0;for await(const part of req.parts()){if(part.type!=='file')continue;if(documents.length>=20)throw new AppError(413,'DOCUMENT_LIMIT','每次最多上传 20 份资料。');const name=safeName(part.filename),ext=extname(name).toLowerCase(),image=['.png','.jpg','.jpeg','.webp'].includes(ext);if(!['.pdf','.docx','.xlsx','.xls','.png','.jpg','.jpeg','.webp'].includes(ext))throw new AppError(400,'UNSUPPORTED_DOCUMENT','仅支持图片、PDF、DOCX、XLSX、XLS 文件。');const buffer=await partBuffer(part,image?10*1024*1024:50*1024*1024);total+=buffer.length;if(total>200*1024*1024)throw new AppError(413,'FILE_TOO_LARGE','一次上传资料合计不能超过 200 MB。');const stored=saveBuffer(rag.directory,buffer,ext.slice(1));documents.push(store.createRagDocument({folderId:req.query.folderId||null,name,storedName:stored,mime:part.mimetype||'application/octet-stream',size:buffer.length}));}if(!documents.length)throw new AppError(400,'EMPTY_UPLOAD','请选择资料文件。');for(const document of documents)void rag.parse(document.id);reply.code(202);return {count:documents.length,items:documents};});
  app.get(prefix+'/rag/export.xlsx',{preHandler:admin,schema:{tags:['知识库技能']}},async(_req,reply)=>{const folders=store.listRagFolders(),documents=store.listRagDocuments(),chunks=store.listRagChunks(),graphs=documents.map(document=>store.getRagGraph(document.id)),files=documents.map(document=>{const stored=store.ragStoredName(document.id);if(!stored)throw new AppError(404,'DOCUMENT_MISSING',`资料“${document.name}”不存在。`);return {documentId:document.id,name:document.name,mime:document.mime,content:readFileSync(join(rag.directory,stored))};}),{buffer,mime}=await createRagWorkbook({folders,documents,chunks,graphs,files}),name=`知识库技能-${new Date().toISOString().slice(0,10)}.xlsx`;reply.header('Content-Type',mime).header('Content-Disposition',`attachment; filename*=UTF-8''${encodeURIComponent(name)}`);return reply.send(buffer);});
  app.get(prefix+'/rag/export-package.zip',{preHandler:admin,schema:{tags:['知识库技能']}},async(_req,reply)=>{
    const folders=store.listRagFolders(),folderNames=new Map(folders.map(folder=>[folder.id,folder.name])),documents=store.listRagDocuments(),chunks=store.listRagChunks(),graphs=documents.map(document=>store.getRagGraph(document.id)),packageFiles:{sourcePath:string;packagePath:string}[]=[],files=documents.map((document,index)=>{const stored=store.ragStoredName(document.id);if(!stored)throw new AppError(404,'DOCUMENT_MISSING',`资料“${document.name}”不存在。`);const sourcePath=join(rag.directory,stored);if(!existsSync(sourcePath))throw new AppError(404,'DOCUMENT_MISSING',`资料“${document.name}”的真实文件不存在。`);const packagePath=ragPackagePath(index+1,document.folderId?folderNames.get(document.folderId)||'未分类':'未分类',document.name);packageFiles.push({sourcePath,packagePath});return {documentId:document.id,name:document.name,mime:document.mime,content:Buffer.alloc(0),packagePath};}),{buffer}=await createRagWorkbook({folders,documents,chunks,graphs,files},{embedAttachments:false,includePackageLinks:true}),date=new Date().toISOString().slice(0,10),name=`知识库技能完整资料包-${date}.zip`,archive=createExportPackage(`知识库技能清单-${date}.xlsx`,buffer,packageFiles);reply.header('Content-Type','application/zip').header('Content-Disposition',`attachment; filename*=UTF-8''${encodeURIComponent(name)}`);return reply.send(archive);
  });
  app.delete<{Params:{id:string}}>(prefix+'/rag/documents/:id',{preHandler:adminWrite,schema:{tags:['知识库技能'],params:ID_PARAMS_SCHEMA}},async req=>{const stored=store.deleteRagDocument(req.params.id);rag.removeFile(stored);return {ok:true};});
  app.post<{Params:{id:string}}>(prefix+'/rag/documents/:id/reparse',{preHandler:adminWrite,schema:{tags:['知识库技能'],params:ID_PARAMS_SCHEMA}},async(req,reply)=>{if(!store.getRagDocument(req.params.id))throw new AppError(404,'NOT_FOUND','资料不存在。');void rag.parse(req.params.id);reply.code(202);return {ok:true};});
  app.get<{Params:{id:string}}>(prefix+'/rag/documents/:id/chunks',{preHandler:admin,schema:{tags:['知识库技能'],params:ID_PARAMS_SCHEMA}},async req=>({items:store.listRagChunks(req.params.id)}));
  app.get<{Params:{id:string}}>(prefix+'/rag/documents/:id/graph',{preHandler:admin,schema:{tags:['知识库技能'],params:ID_PARAMS_SCHEMA}},async req=>store.getRagGraph(req.params.id));
  app.get(prefix+'/rag/settings',{preHandler:admin,schema:{tags:['知识库技能']}},async()=>store.getRagSettings());
  app.patch<{Body:Omit<RagSettings,'updatedAt'>}>(prefix+'/rag/settings',{preHandler:adminWrite,schema:{tags:['知识库技能'],body:{type:'object',additionalProperties:false,required:['embeddingModel','rerankModel','parserMode','chunkSize','chunkOverlap','topK'],properties:{embeddingModel:{type:'string',maxLength:100},rerankModel:{type:'string',maxLength:100},parserMode:{enum:['local','model']},chunkSize:{type:'integer',minimum:200,maximum:2400},chunkOverlap:{type:'integer',minimum:0,maximum:1000},topK:{type:'integer',minimum:1,maximum:20}}}}},async req=>store.saveRagSettings(req.body));
  app.get<{Querystring:{type:'embedding'|'rerank'}}>(prefix+'/rag/models',{preHandler:admin,schema:{tags:['知识库技能'],querystring:{type:'object',additionalProperties:false,required:['type'],properties:{type:{enum:['embedding','rerank']}}}}},async req=>({groups:req.query.type==='embedding'?[{provider:'统一 Chunk 集合',items:[{id:'local/hash-384',name:'Hash Embedding 384D'},{id:'local/tfidf',name:'TF-IDF 768D'}]}]:[{provider:'LangChain 混合检索',items:[{id:'langchain/ensemble-rrf',name:'EnsembleRetriever 加权 RRF'}]}]}));
  app.post<{Body:{question:string;topK?:number}}>(prefix+'/rag/search',{preHandler:adminWrite,schema:{tags:['知识库技能'],body:{type:'object',additionalProperties:false,required:['question'],properties:{question:{type:'string',minLength:1,maxLength:200},topK:{type:'integer',minimum:1,maximum:20}}}}},async req=>({items:await rag.searchWithRerank(req.body.question,req.body.topK)}));
  app.post<{Body:{cases:RagEvaluationCase[]}}>(prefix+'/rag/evaluate',{
    preHandler:adminWrite,
    schema:{tags:['知识库技能'],body:{type:'object',additionalProperties:false,required:['cases'],properties:{
      cases:{type:'array',minItems:1,maxItems:50,items:{type:'object',additionalProperties:false,required:['question','expectedAnswer'],properties:{question:{type:'string',minLength:1,maxLength:200},expectedAnswer:{type:'string',minLength:1,maxLength:1500}}}},
    }}},
  },async req=>rag.evaluate(req.body.cases));
  }
  if(phase==='materials'||phase==='all') {
  app.get(prefix+'/admin/materials/categories',{preHandler:admin,schema:{tags:['资料整理']}},async()=>({items:store.listMaterialCategories()}));
  app.post<{Body:{name:string}}>(prefix+'/admin/materials/categories',{preHandler:adminWrite,schema:{tags:['资料整理'],body:{type:'object',additionalProperties:false,required:['name'],properties:{name:{type:'string',minLength:1,maxLength:60}}}}},async(req,reply)=>{reply.code(201);return store.createMaterialCategory(req.body.name);});
  app.patch<{Params:{id:string};Body:{name:string}}>(prefix+'/admin/materials/categories/:id',{preHandler:adminWrite,schema:{tags:['资料整理'],params:ID_PARAMS_SCHEMA,body:{type:'object',additionalProperties:false,required:['name'],properties:{name:{type:'string',minLength:1,maxLength:60}}}}},async req=>store.renameMaterialCategory(req.params.id,req.body.name));
  app.delete<{Params:{id:string}}>(prefix+'/admin/materials/categories/:id',{preHandler:adminWrite,schema:{tags:['资料整理'],params:ID_PARAMS_SCHEMA}},async req=>store.deleteMaterialCategory(req.params.id));
  app.get<{Querystring:{q?:string;status?:MaterialStatus;categoryId?:string;page?:number;pageSize?:number}}>(prefix+'/admin/materials',{preHandler:admin,schema:{tags:['资料整理'],querystring:{type:'object',additionalProperties:false,properties:{q:{type:'string',maxLength:200},status:{enum:['pending_confirm','pending_archive','archived']},categoryId:{type:'string',maxLength:100},page:{type:'integer',minimum:1,default:1},pageSize:{type:'integer',minimum:1,maximum:100,default:10}}}}},async req=>store.listMaterialItems(req.query));
  app.patch<{Params:{id:string};Body:{categoryId:string|null}}>(prefix+'/admin/materials/:id',{preHandler:adminWrite,schema:{tags:['资料整理'],params:ID_PARAMS_SCHEMA,body:{type:'object',additionalProperties:false,required:['categoryId'],properties:{categoryId:{anyOf:[{type:'string',minLength:1,maxLength:100},{type:'null'}]}}}}},async req=>store.updateMaterialItem(req.params.id,req.body.categoryId));
  app.get<{Params:{id:string}}>(prefix+'/admin/materials/:id/download',{preHandler:admin,schema:{tags:['资料整理'],params:ID_PARAMS_SCHEMA}},async(req,reply)=>{const file=store.materialItemFile(req.params.id);if(!file)throw new AppError(404,'NOT_FOUND','资料不存在。');const path=join(materialDirectory,file.stored_name);if(!existsSync(path))throw new AppError(404,'FILE_MISSING','资料文件不存在。');reply.header('Content-Type',file.mime).header('Content-Length',String(file.size)).header('Content-Disposition',`attachment; filename*=UTF-8''${encodeURIComponent(file.name)}`);return reply.send(createReadStream(path));});
  app.get<{Querystring:{ids:string}}>(prefix+'/admin/materials/download.zip',{preHandler:admin,schema:{tags:['资料整理'],querystring:{type:'object',additionalProperties:false,required:['ids'],properties:{ids:{type:'string',minLength:8,maxLength:10000}}}}},async(req,reply)=>{const ids=[...new Set(req.query.ids.split(',').filter(id=>/^[A-Za-z0-9_-]{8,100}$/.test(id)))].slice(0,100);if(!ids.length)throw new AppError(400,'INVALID_SELECTION','请选择资料。');const files=ids.map(id=>store.materialItemFile(id)).filter(Boolean) as NonNullable<ReturnType<Store['materialItemFile']>>[];if(!files.length)throw new AppError(404,'NOT_FOUND','资料不存在。');const used=new Map<string,number>(),entries=files.map((file,index)=>{const count=(used.get(file.name)||0)+1;used.set(file.name,count);const name=count===1?file.name:`${String(index+1).padStart(2,'0')}-${file.name}`;return {sourcePath:join(materialDirectory,file.stored_name),packagePath:safeName(name)};});reply.header('Content-Type','application/zip').header('Content-Disposition',`attachment; filename*=UTF-8''${encodeURIComponent('资料整理-'+new Date().toISOString().slice(0,10)+'.zip')}`);return reply.send(createFileArchive(entries));});
  app.delete<{Params:{id:string}}>(prefix+'/admin/materials/:id',{preHandler:adminWrite,schema:{tags:['资料整理'],params:ID_PARAMS_SCHEMA}},async req=>{const rows=store.deleteMaterialItems([req.params.id]);for(const row of rows)rmSync(join(materialDirectory,row.stored_name),{force:true});return {ok:true,id:req.params.id};});
  app.delete<{Body:{ids:string[]}}>(prefix+'/admin/materials',{preHandler:adminWrite,schema:{tags:['资料整理'],body:{type:'object',additionalProperties:false,required:['ids'],properties:{ids:{type:'array',minItems:1,maxItems:100,uniqueItems:true,items:{type:'string',minLength:8,maxLength:100}}}}}},async req=>{const rows=store.deleteMaterialItems(req.body.ids);for(const row of rows)rmSync(join(materialDirectory,row.stored_name),{force:true});return {ok:true,count:rows.length};});
  }
}
