import Fastify, { LogController, type FastifyRequest } from 'fastify';
import cookie from '@fastify/cookie';
import cors from '@fastify/cors';
import helmet from '@fastify/helmet';
import rateLimit from '@fastify/rate-limit';
import swagger from '@fastify/swagger';
import multipart from '@fastify/multipart';
import { randomUUID } from 'node:crypto';
import { createReadStream,existsSync,mkdirSync,readFileSync,rmSync } from 'node:fs';
import { extname,join } from 'node:path';
import type { AnswerInput,FaqLibraryType,MaterialStatus,TextModelProvider,FaqInput,NotificationInput,RagEvaluationCase,RagSettings,SessionResult } from '@campus/contracts';
import { ANSWER_INPUT_SCHEMA,ANSWER_RESPONSE_SCHEMA,FAQ_INPUT_SCHEMA,FAQ_PATCH_SCHEMA,PAGE_QUERY_SCHEMA } from '@campus/contracts';
import { loadConfig,type Config } from './config.js';
import { Store,hash,type ListQuery } from './db/store.js';
import { AppError } from './errors.js';
import { login,constantEqual,hashPassword } from './services/auth.js';
import { AnswerService } from './services/answer.js';
import { BotControlError,LocalBotController,type BotController } from './services/bot-control.js';
import { Models } from './services/models.js';
import { QqGroups } from './services/qq-groups.js';
import { type ModelSelector } from './services/model.js';
import { RagService } from './services/rag.js';
import { attachmentKind,notificationAttachmentKind,partBuffer,safeName,saveBuffer,saveFolderZip } from './services/uploads.js';
import { createFaqWorkbook,parseFaqWorkbook } from './services/faq-workbook.js';
import { createRagWorkbook } from './services/rag-workbook.js';
import { createExportPackage,createFileArchive,faqPackagePath,ragPackagePath } from './services/export-package.js';
import { MaterialInboxService,materialSourceKey } from './services/materials.js';
import { AnswerOptimizer } from './services/answer-optimizer.js';

declare module 'fastify' { interface FastifyRequest { campusSession?:SessionResult } }
const idParams={type:'object',additionalProperties:false,required:['id'],properties:{id:{type:'string',minLength:1,maxLength:100}}};
export async function createApp(overrides:Partial<Config>={},dependencies:{store?:Store;select?:ModelSelector;modelFetch?:typeof fetch;botController?:BotController}={}) {
  const config=loadConfig(overrides),store=dependencies.store||new Store(config.dbPath,config.root);store.lockDeveloperAccess();
  if(config.developerPassword)await store.ensureDeveloper(config.developerUsername,await hashPassword(config.developerPassword));
  const app=Fastify({bodyLimit:32768,logger:config.logger,logController:new LogController({disableRequestLogging:true}),genReqId:()=>randomUUID(),trustProxy:['127.0.0.1','::1'],ajv:{customOptions:{removeAdditional:false,coerceTypes:'array',allErrors:false}}});
  app.decorateRequest('campusSession',undefined);
  await app.register(cookie);
  await app.register(multipart,{limits:{files:200,fileSize:25*1024*1024,parts:220},preservePath:true});
  await app.register(cors,{origin:(origin,cb)=>cb(null,!origin||config.origins.includes(origin)),credentials:true,methods:['GET','POST','PATCH','DELETE','OPTIONS'],allowedHeaders:['Content-Type','X-CSRF-Token','Authorization']});
  await app.register(helmet);
  await app.register(rateLimit,{max:Math.max(120,config.rateLimit),timeWindow:'1 minute',keyGenerator:req=>hash(req.ip),errorResponseBuilder:()=>new AppError(429,'RATE_LIMITED','操作过于频繁，请稍后重试。')});
  await app.register(swagger,{openapi:{info:{title:'校园教务小助手 API',version:'1.0.0'},servers:[{url:'/'}]}});
  const models=new Models(config,config.dbPath===':memory:',dependencies.modelFetch||fetch,dependencies.select);
  if(config.dbPath!==':memory:')for(const provider of ['deepseek','zhipu'] as const)if(store.servicePreference(`${provider}_auto_start`)&&models.settings.read(provider).apiKey)models.settings.connected(provider,true);
  const answers=new AnswerService(store,config,dependencies.select,models),answerOptimizer=new AnswerOptimizer(models);
  const rag=new RagService(store,config,models);answers.rag=rag;
  const materials=new MaterialInboxService(store,models),materialDirectory=join(config.dataDir,'material-inbox');mkdirSync(materialDirectory,{recursive:true});
  const botController=dependencies.botController||new LocalBotController(config.root,config.botToken,config.dataDir,config.localDir);
  const qqGroups=new QqGroups(store,config.dataDir);
  let botState:{state:'connected'|'offline';lastSeen:number}|null=null;
  const publicStatus=()=>{const s=store.stats();return {activeFaqs:s.activeFaqs,demoMode:s.demoMode,modelConfigured:models.available(),mode:models.available()?'semantic':'faq',service:'校园教务小助手'};};
  function originGuard(req:FastifyRequest) {if(req.headers.origin&&!config.origins.includes(req.headers.origin))throw new AppError(403,'ORIGIN_REJECTED','请求来源不被允许。');}
  async function session(req:FastifyRequest) { const token=req.cookies.campus_session;const found=token?store.getSession(token):undefined;if(!found)throw new AppError(401,'UNAUTHORIZED','请先登录。');req.campusSession={user:found.user,csrfToken:found.csrfToken};if(found.workspaceId)store.enterWorkspace(found.workspaceId); }
  async function admin(req:FastifyRequest) {await session(req);if(req.campusSession!.user.role!=='teacher')throw new AppError(403,'TEACHER_REQUIRED','开发者账号不能访问老师业务数据。');}
  async function adminWrite(req:FastifyRequest) {await admin(req);originGuard(req);if(typeof req.headers['x-csrf-token']!=='string'||!constantEqual(req.headers['x-csrf-token'],req.campusSession!.csrfToken))throw new AppError(403,'CSRF_REJECTED','页面凭证已失效，请刷新后重试。');}
  async function sessionWrite(req:FastifyRequest){await session(req);originGuard(req);if(typeof req.headers['x-csrf-token']!=='string'||!constantEqual(req.headers['x-csrf-token'],req.campusSession!.csrfToken))throw new AppError(403,'CSRF_REJECTED','页面凭证已失效，请刷新后重试。');}
  async function developerAccount(req:FastifyRequest){await session(req);if(req.campusSession!.user.role!=='developer')throw new AppError(403,'DEVELOPER_REQUIRED','仅开发者账号可以访问账号管理。');}
  async function developerAccountWrite(req:FastifyRequest){await sessionWrite(req);if(req.campusSession!.user.role!=='developer')throw new AppError(403,'DEVELOPER_REQUIRED','仅开发者账号可以访问账号管理。');}
  async function developerWrite(req:FastifyRequest){await adminWrite(req);if(!store.developerAccess(req.cookies.campus_session!).unlocked)throw new AppError(403,'DEVELOPER_LOCKED','请先输入开发者密匙。');}
  async function bot(req:FastifyRequest) {const expected=config.botToken;if(!expected||!constantEqual(req.headers.authorization||'',`Bearer ${expected}`))throw new AppError(401,'BOT_UNAUTHORIZED','机器人服务凭证无效。');store.enterWorkspace(store.botWorkspace());const appId=req.headers['x-qq-app-id'];if(appId&&appId!==botController.status().appId)throw new AppError(409,'BOT_CHANGED','当前机器人已更换，请停止旧连接。');}
  app.setErrorHandler((error,req,reply)=>{
    const err=error as Error & {statusCode?:number;validation?:unknown;code?:string};
    let status=err.statusCode||500,code=err.code||'INTERNAL_ERROR',message='服务暂不可用，请稍后重试。';
    if(err.validation){status=400;code='INVALID_INPUT';message='提交内容格式不正确，请检查字段和长度。';}
    else if(err instanceof AppError)message=err.message;
    else if(err instanceof BotControlError){status=err.statusCode;code=err.code;message=err.message;}
    else if(status===429){code='RATE_LIMITED';message='操作过于频繁，请稍后重试。';}
    else if(err.code?.startsWith('SQLITE_')||/database connection is not open/i.test(err.message)){status=503;code='DATABASE_UNAVAILABLE';}
    else if(status===400||status===415){code='INVALID_INPUT';message='请使用有效的 JSON 请求。';}
    if(status>=500)req.log.error({code,status,requestId:req.id},'请求处理失败');
    reply.code(status).send({error:{code,message},requestId:req.id});
  });
  app.setNotFoundHandler((req,reply)=>reply.code(404).send({error:{code:'NOT_FOUND',message:'接口不存在。'},requestId:req.id}));
  app.addHook('onResponse',async(req,reply)=>{req.log.info({requestId:req.id,method:req.method,route:req.routeOptions.url||'unknown',status:reply.statusCode,elapsedMs:Math.round(reply.elapsedTime)},'请求完成');});
  const sessionCookie={path:'/',httpOnly:true,sameSite:'lax' as const,secure:config.cookieSecure,maxAge:8*3600};
  const prefix='/api/v1';
  app.get(prefix+'/health/live',{config:{rateLimit:false}},async()=>({ok:true}));
  app.get(prefix+'/health/ready',{config:{rateLimit:false}},async()=>{try{store.sqlite.prepare('SELECT 1').get();return {ok:true};}catch{throw new AppError(503,'DATABASE_UNAVAILABLE','数据库尚未就绪。');}});
  app.get(prefix+'/status',async()=>publicStatus());

  app.post<{Body:{username:string;password:string}}>(prefix+'/auth/login',{
    schema:{tags:['认证'],body:{type:'object',additionalProperties:false,required:['username','password'],properties:{username:{type:'string',minLength:1,maxLength:40},password:{type:'string',minLength:1,maxLength:128}}}},
    preHandler:async(req)=>originGuard(req),config:{rateLimit:{max:config.loginRateLimit,timeWindow:'1 minute'}},
  },async(req,reply)=>{const result=await login(store,req.body.username,req.body.password);reply.setCookie('campus_session',result.token,sessionCookie);return {user:result.user,csrfToken:result.csrfToken};});
  app.post<{Body:{username:string;password:string;registrationCode:string}}>(prefix+'/auth/register',{preHandler:async req=>originGuard(req),config:{rateLimit:{max:3,timeWindow:'1 minute'}},schema:{tags:['认证'],body:{type:'object',additionalProperties:false,required:['username','password','registrationCode'],properties:{username:{type:'string',minLength:2,maxLength:40},password:{type:'string',minLength:12,maxLength:128},registrationCode:{type:'string',minLength:1,maxLength:32}}}}},async(req,reply)=>{if(!constantEqual(req.body.registrationCode,config.registrationCode))throw new AppError(403,'INVALID_REGISTRATION_CODE','注册码不正确。');const account=store.registerAdmin(req.body.username,await hashPassword(req.body.password));const result=await login(store,account.username,req.body.password);reply.setCookie('campus_session',result.token,sessionCookie).code(201);return {user:result.user,csrfToken:result.csrfToken};});
  app.get(prefix+'/auth/session',{preHandler:session,schema:{tags:['认证']}},async req=>req.campusSession);
  app.post(prefix+'/auth/logout',{preHandler:sessionWrite,schema:{tags:['认证']}},async(req,reply)=>{store.deleteSession(req.cookies.campus_session!);reply.clearCookie('campus_session',{path:'/'});return {ok:true};});
  app.get(prefix+'/developer/accounts',{preHandler:developerAccount,schema:{tags:['账户管理']}},async()=>({items:store.listRegisteredAccounts()}));
  app.post<{Params:{id:string};Body:{password:string}}>(prefix+'/developer/accounts/:id/reset-password',{preHandler:developerAccountWrite,config:{rateLimit:{max:5,timeWindow:'1 minute'}},schema:{tags:['账户管理'],params:idParams,body:{type:'object',additionalProperties:false,required:['password'],properties:{password:{type:'string',minLength:12,maxLength:128}}}}},async req=>store.resetRegisteredAccount(req.params.id,await hashPassword(req.body.password)));
  app.post<{Body:AnswerInput}>(prefix+'/internal/qq/answer',{bodyLimit:8500000,preHandler:bot,schema:{tags:['QQ'],body:ANSWER_INPUT_SCHEMA,response:{200:ANSWER_RESPONSE_SCHEMA}},config:{rateLimit:{max:120,timeWindow:'1 minute'}}},req=>answers.answer(req.body,'qq'));
  app.post(prefix+'/internal/qq/transcribe',{bodyLimit:27*1024*1024,preHandler:bot,config:{rateLimit:{max:60,timeWindow:'1 minute'}},schema:{hide:true}},async req=>{let audio:{buffer:Buffer;mime:string;name:string}|null=null;for await(const part of req.parts()){if(part.type!=='file'||part.fieldname!=='audio')continue;if(audio)throw new AppError(400,'AUDIO_LIMIT','每次只能识别一条语音。');audio={buffer:await partBuffer(part,25*1024*1024),mime:part.mimetype||'application/octet-stream',name:safeName(part.filename)};}if(!audio)throw new AppError(400,'EMPTY_AUDIO','没有收到语音文件。');return {text:await models.transcribeAudio(audio.buffer,audio.mime,audio.name)};});
  app.post(prefix+'/internal/qq/materials',{bodyLimit:27*1024*1024,preHandler:bot,config:{rateLimit:{max:120,timeWindow:'1 minute'}},schema:{hide:true}},async(req,reply)=>{let metadataText='',file:{buffer:Buffer;mime:string;name:string}|null=null;for await(const part of req.parts()){if(part.type==='field'){if(part.fieldname==='metadata')metadataText=String(part.value);continue;}if(part.fieldname!=='file'||file)throw new AppError(400,'MATERIAL_FILE_LIMIT','每次只能接收一个资料文件。');file={buffer:await partBuffer(part,25*1024*1024),mime:part.mimetype||'application/octet-stream',name:safeName(part.filename)};}if(!file)throw new AppError(400,'EMPTY_UPLOAD','没有收到资料文件。');let metadata:{messageId:string;senderId:string;senderName?:string};try{metadata=JSON.parse(metadataText);}catch{throw new AppError(400,'INVALID_MATERIAL_METADATA','资料来源信息无效。');}if(typeof metadata.messageId!=='string'||!metadata.messageId||metadata.messageId.length>200||/[\p{Cc}\p{Cf}]/u.test(metadata.messageId)||!/^[A-Za-z0-9_-]{1,160}$/.test(metadata.senderId)||metadata.senderName&&metadata.senderName.length>80)throw new AppError(400,'INVALID_MATERIAL_METADATA','资料来源信息无效。');const extension=extname(file.name).toLowerCase(),allowed=new Set(['.pdf','.doc','.docx','.xls','.xlsx','.ppt','.pptx','.txt','.csv','.zip','.rar','.7z']);if(!allowed.has(extension))throw new AppError(400,'UNSUPPORTED_MATERIAL','资料仅支持 PPT、PDF、Word、Excel 及常用文档压缩包。');const sourceKey=materialSourceKey(metadata.messageId,file.name,file.buffer.length),existing=store.materialBySourceKey(sourceKey);if(existing){reply.code(200);return existing;}const categoryId=await materials.classify(file.name,store.listMaterialCategories()),storedName=saveBuffer(materialDirectory,file.buffer,extension.slice(1));try{const item=store.createMaterialItem({sourceKey,categoryId,name:file.name,storedName,mime:file.mime,size:file.buffer.length,senderId:metadata.senderId,senderName:metadata.senderName});reply.code(201);return item;}catch(error){rmSync(join(materialDirectory,storedName),{force:true});throw error;}});
  app.get<{Params:{id:string}}>(prefix+'/internal/qq/attachments/:id',{preHandler:bot,schema:{hide:true,params:idParams}},async(req,reply)=>{const faqFile=store.attachmentFile(req.params.id),ragFile=faqFile?undefined:store.ragFile(req.params.id),notificationFile=faqFile||ragFile?undefined:store.notificationAttachmentFile(req.params.id),file=faqFile||ragFile||notificationFile;if(!file)throw new AppError(404,'NOT_FOUND','附件不存在。');const path=faqFile?join(config.dataDir,'faq-attachments',faqFile.faq_id,faqFile.stored_name):ragFile?join(rag.directory,ragFile.stored_name):join(config.dataDir,'notification-attachments',notificationFile!.stored_name);reply.header('Content-Type',file.mime).header('Content-Length',String(file.size)).header('Content-Disposition',`attachment; filename*=UTF-8''${encodeURIComponent(file.name)}`);return reply.send(createReadStream(path));});
  app.post<{Body:{state:'connected'|'offline'}}>(prefix+'/internal/qq/heartbeat',{preHandler:bot,schema:{hide:true,body:{type:'object',additionalProperties:false,required:['state'],properties:{state:{enum:['connected','offline']}}}}},async req=>{botState={state:req.body.state,lastSeen:Date.now()};return {ok:true};});
  app.get(prefix+'/internal/qq/offline/preferences',{preHandler:bot,schema:{hide:true}},async()=>store.unmatchedPreferences());
  app.post<{Body:{question:string;qqSender?:AnswerInput['qqSender']}}>(prefix+'/internal/qq/offline/questions',{preHandler:bot,schema:{hide:true,body:{type:'object',additionalProperties:false,required:['question'],properties:{question:{type:'string',minLength:1,maxLength:200},qqSender:ANSWER_INPUT_SCHEMA.properties.qqSender}}}},async(req,reply)=>{const result=store.recordOfflineQuestion(req.body.question,req.body.qqSender);reply.code(201);return result;});
  app.post<{Params:{id:string}}>(prefix+'/internal/qq/offline/questions/:id/complete',{preHandler:bot,schema:{hide:true,params:idParams}},async req=>store.completeOfflineQuestion(req.params.id));
  app.post<{Body:{openId:string}}>(prefix+'/internal/qq/groups',{preHandler:bot,schema:{hide:true,body:{type:'object',additionalProperties:false,required:['openId'],properties:{openId:{type:'string',minLength:6,maxLength:160,pattern:'^[A-Za-z0-9_-]+$'}}}}},async req=>{const group=store.registerQqGroup(req.body.openId,botController.status().appId);if(!group.nameSynced)qqGroups.invalidate();return group;});
  app.post<{Body:{limit?:number}}>(prefix+'/internal/qq/notifications/claim',{preHandler:bot,schema:{hide:true,body:{type:'object',additionalProperties:false,properties:{limit:{type:'integer',minimum:1,maximum:20,default:5}}}}},async req=>({items:store.claimNotificationTargets(req.body.limit,botController.status().appId||undefined)}));
  app.post<{Params:{id:string};Body:{claimToken:string}}>(prefix+'/internal/qq/notifications/:id/begin',{preHandler:bot,schema:{hide:true,params:idParams,body:{type:'object',additionalProperties:false,required:['claimToken'],properties:{claimToken:{type:'string',minLength:36,maxLength:36}}}}},async req=>store.beginNotificationTarget(req.params.id,req.body.claimToken));
  app.post<{Params:{id:string};Body:{claimToken:string;status:'sent'|'failed';errorCode?:string;messageId?:string}}>(prefix+'/internal/qq/notifications/:id/result',{preHandler:bot,schema:{hide:true,params:idParams,body:{type:'object',additionalProperties:false,required:['claimToken','status'],properties:{claimToken:{type:'string',minLength:36,maxLength:36},status:{enum:['sent','failed']},errorCode:{type:'string',maxLength:120},messageId:{type:'string',minLength:1,maxLength:200}}}}},async req=>store.completeNotificationTarget(req.params.id,req.body.claimToken,req.body.status,req.body.errorCode,req.body.messageId));
  app.post<{Body:{limit?:number}}>(prefix+'/internal/qq/unmatched-replies/claim',{preHandler:bot,schema:{hide:true,body:{type:'object',additionalProperties:false,properties:{limit:{type:'integer',minimum:1,maximum:20,default:5}}}}},async req=>({items:store.claimUnmatchedReplies(req.body.limit)}));
  app.post<{Params:{id:string};Body:{claimToken:string}}>(prefix+'/internal/qq/unmatched-replies/:id/begin',{preHandler:bot,schema:{hide:true,params:idParams,body:{type:'object',additionalProperties:false,required:['claimToken'],properties:{claimToken:{type:'string',minLength:36,maxLength:36}}}}},async req=>store.beginUnmatchedReply(req.params.id,req.body.claimToken));
  app.post<{Params:{id:string};Body:{claimToken:string;status:'sent'|'failed';errorCode?:string;messageId?:string}}>(prefix+'/internal/qq/unmatched-replies/:id/result',{preHandler:bot,schema:{hide:true,params:idParams,body:{type:'object',additionalProperties:false,required:['claimToken','status'],properties:{claimToken:{type:'string',minLength:36,maxLength:36},status:{enum:['sent','failed']},errorCode:{type:'string',maxLength:120},messageId:{type:'string',minLength:1,maxLength:200}}}}},async req=>store.completeUnmatchedReply(req.params.id,req.body.claimToken,req.body.status,req.body.errorCode,req.body.messageId));
  app.get<{Querystring:ListQuery}>(prefix+'/faqs',{preHandler:admin,schema:{tags:['FAQ'],querystring:PAGE_QUERY_SCHEMA}},async req=>store.listFaqs(req.query));
  app.post<{Body:FaqInput}>(prefix+'/faqs',{preHandler:adminWrite,schema:{tags:['FAQ'],body:FAQ_INPUT_SCHEMA}},async(req,reply)=>{const result=store.saveFaq(req.body,req.campusSession!.user.id);reply.code(201);return result;});
  app.post<{Body:{ids:string[];libraryType:FaqLibraryType;action:'update'|'delete';category?:string;status?:'active'|'disabled'}}>(prefix+'/faqs/batch',{preHandler:adminWrite,schema:{tags:['FAQ'],body:{type:'object',additionalProperties:false,required:['ids','libraryType','action'],properties:{ids:{type:'array',minItems:1,maxItems:100,uniqueItems:true,items:{type:'string',minLength:8,maxLength:100}},libraryType:{enum:['answer','forbidden']},action:{enum:['update','delete']},category:{type:'string',minLength:1,maxLength:40},status:{enum:['active','disabled']}}}}},async req=>{const result=store.batchFaqs(req.body.ids,req.body.libraryType,req.body.action,req.campusSession!.user.id,{category:req.body.category,status:req.body.status});if(req.body.action==='delete')for(const id of result.deletedIds)rmSync(join(config.dataDir,'faq-attachments',id),{recursive:true,force:true});return result;});
  app.post(prefix+'/faqs/abuse-lexicon/import',{preHandler:adminWrite,schema:{tags:['FAQ']}},async req=>store.importAbuseLexicon(req.campusSession!.user.id));
  app.post<{Body:{question:string;answer:string}}>(prefix+'/faqs/optimize-answer',{preHandler:adminWrite,config:{rateLimit:{max:20,timeWindow:'1 minute'}},schema:{tags:['FAQ'],body:{type:'object',additionalProperties:false,required:['question','answer'],properties:{question:{type:'string',maxLength:200},answer:{type:'string',minLength:1,maxLength:1500}}}}},async req=>answerOptimizer.optimize(req.body.question,req.body.answer));
  app.patch<{Params:{id:string};Body:FaqInput&{version:number}}>(prefix+'/faqs/:id',{preHandler:adminWrite,schema:{tags:['FAQ'],params:idParams,body:FAQ_PATCH_SCHEMA}},async req=>store.saveFaq(req.body,req.campusSession!.user.id,req.params.id,req.body.version));
  app.delete<{Params:{id:string};Body:{version:number}}>(prefix+'/faqs/:id',{preHandler:adminWrite,schema:{tags:['FAQ'],params:idParams,body:{type:'object',additionalProperties:false,required:['version'],properties:{version:{type:'integer',minimum:1}}}}},async req=>{const deleted=store.deleteFaq(req.params.id,req.campusSession!.user.id,req.body.version);rmSync(join(config.dataDir,'faq-attachments',deleted.id),{recursive:true,force:true});return {ok:true,id:deleted.id};});
  app.get<{Querystring:{libraryType?:FaqLibraryType}}>(prefix+'/faqs/export',{preHandler:admin,schema:{tags:['FAQ'],querystring:{type:'object',additionalProperties:false,properties:{libraryType:{enum:['answer','forbidden']}}}}},async req=>({version:1,exportedAt:Date.now(),libraryType:req.query.libraryType||'answer',items:store.listFaqs({libraryType:req.query.libraryType||'answer',pageSize:100}).items.map(({attachments:_,...faq})=>faq)}));
  app.post<{Body:{items:(FaqInput&{id?:string})[]}}>(prefix+'/faqs/import',{preHandler:adminWrite,schema:{tags:['FAQ'],body:{type:'object',additionalProperties:false,required:['items'],properties:{items:{type:'array',minItems:1,maxItems:1000,items:{...FAQ_INPUT_SCHEMA,properties:{...FAQ_INPUT_SCHEMA.properties,id:{type:'string',maxLength:100}}}}}}}},async(req,reply)=>{const items=store.importFaqs(req.body.items,req.campusSession!.user.id);reply.code(201);return {count:items.length,items};});
  app.get<{Querystring:{libraryType?:FaqLibraryType}}>(prefix+'/faqs/export.xlsx',{preHandler:admin,schema:{tags:['FAQ'],querystring:{type:'object',additionalProperties:false,properties:{libraryType:{enum:['answer','forbidden']}}}}},async(req,reply)=>{const libraryType=req.query.libraryType||'answer',items=store.listFaqsForExport(libraryType),{buffer,mime}=await createFaqWorkbook(items,libraryType),name=`${libraryType==='answer'?'答疑题库':'敏感词库'}-${new Date().toISOString().slice(0,10)}.xlsx`;reply.header('Content-Type',mime).header('Content-Disposition',`attachment; filename*=UTF-8''${encodeURIComponent(name)}`).header('Cache-Control','no-store');return reply.send(buffer);});
  app.get<{Querystring:{libraryType?:FaqLibraryType}}>(prefix+'/faqs/export-package.zip',{preHandler:admin,schema:{tags:['FAQ'],querystring:{type:'object',additionalProperties:false,properties:{libraryType:{enum:['answer','forbidden']}}}}},async(req,reply)=>{
    const libraryType=req.query.libraryType||'answer',items=store.listFaqs({libraryType,pageSize:10000}).items,packageFiles:{sourcePath:string;packagePath:string}[]=[],attachments=libraryType==='answer'?items.flatMap((item,itemIndex)=>(item.attachments||[]).map((meta,attachmentIndex)=>{const file=store.attachmentFile(meta.id);if(!file)throw new AppError(404,'ATTACHMENT_MISSING',`附件“${meta.name}”不存在。`);const sourcePath=join(config.dataDir,'faq-attachments',file.faq_id,file.stored_name);if(!existsSync(sourcePath))throw new AppError(404,'ATTACHMENT_MISSING',`附件“${meta.name}”的真实文件不存在。`);const packagePath=faqPackagePath(itemIndex+1,item.question,attachmentIndex+1,file.name);packageFiles.push({sourcePath,packagePath});return {faqId:item.id,name:file.name,kind:file.kind,mime:file.mime,content:Buffer.alloc(0),packagePath};})):[];
    const title=libraryType==='answer'?'答疑题库':'敏感词库',{buffer}=await createFaqWorkbook(items,libraryType,attachments,{embedAttachments:false,includePackageLinks:true}),date=new Date().toISOString().slice(0,10),name=`${title}完整资料包-${date}.zip`,archive=createExportPackage(`${title}清单-${date}.xlsx`,buffer,packageFiles);reply.header('Content-Type','application/zip').header('Content-Disposition',`attachment; filename*=UTF-8''${encodeURIComponent(name)}`);return reply.send(archive);
  });
  app.post<{Querystring:{libraryType?:FaqLibraryType}}>(prefix+'/faqs/import.xlsx',{bodyLimit:55*1024*1024,preHandler:adminWrite,schema:{tags:['FAQ'],querystring:{type:'object',additionalProperties:false,properties:{libraryType:{enum:['answer','forbidden']}}}}},async(req,reply)=>{const libraryType=req.query.libraryType||'answer',items:FaqInput[]=[];let count=0,total=0;for await(const part of req.parts()){if(part.type!=='file')continue;if(extname(part.filename).toLowerCase()!=='.xlsx')throw new AppError(400,'INVALID_XLSX','请选择系统导出的 .xlsx 固定模板。');const buffer=await partBuffer(part,10*1024*1024);total+=buffer.length;if(++count>20||total>50*1024*1024)throw new AppError(413,'XLSX_LIMIT','每次最多导入 20 个、合计 50 MB 的 Excel 文件。');items.push(...await parseFaqWorkbook(buffer,libraryType));}if(!items.length)throw new AppError(400,'INVALID_XLSX','请选择系统导出的 .xlsx 固定模板。');const saved=store.transaction(()=>{const known=new Set(store.listCategories(libraryType).map(x=>x.name));for(const item of items){if(!known.has(item.category)){store.createCategory(item.category,libraryType);known.add(item.category);}}return store.importFaqs(items,req.campusSession!.user.id);});reply.code(201);return {count:saved.length};});
  app.get<{Querystring:{libraryType:FaqLibraryType}}>(prefix+'/knowledge/categories',{preHandler:admin,schema:{tags:['知识库'],querystring:{type:'object',additionalProperties:false,required:['libraryType'],properties:{libraryType:{enum:['answer','forbidden']}}}}},async req=>({items:store.listCategories(req.query.libraryType)}));
  app.post<{Body:{name:string;libraryType:FaqLibraryType}}>(prefix+'/knowledge/categories',{preHandler:adminWrite,schema:{tags:['知识库'],body:{type:'object',additionalProperties:false,required:['name','libraryType'],properties:{name:{type:'string',minLength:1,maxLength:40},libraryType:{enum:['answer','forbidden']}}}}},async(req,reply)=>{const result=store.createCategory(req.body.name,req.body.libraryType);reply.code(201);return result;});
  app.patch<{Params:{id:string};Body:{name:string}}>(prefix+'/knowledge/categories/:id',{preHandler:adminWrite,schema:{tags:['知识库'],params:idParams,body:{type:'object',additionalProperties:false,required:['name'],properties:{name:{type:'string',minLength:1,maxLength:40}}}}},async req=>store.renameCategory(req.params.id,req.body.name));
  app.delete<{Params:{id:string}}>(prefix+'/knowledge/categories/:id',{preHandler:adminWrite,schema:{tags:['知识库'],params:idParams}},async req=>store.deleteCategory(req.params.id));
  app.post<{Params:{id:string};Querystring:{kind?:'folder';folderName?:string}}>(prefix+'/faqs/:id/attachments',{bodyLimit:70*1024*1024,preHandler:adminWrite,schema:{tags:['FAQ 附件'],params:idParams,querystring:{type:'object',additionalProperties:false,properties:{kind:{enum:['folder']},folderName:{type:'string',maxLength:100}}}}},async(req,reply)=>{const faq=store.getFaq(req.params.id);if(!faq)throw new AppError(404,'NOT_FOUND','知识条目不存在。');const existing=store.listFaqAttachments(faq.id),files:{name:string;mime:string;buffer:Buffer}[]=[];let total=0;for await(const part of req.parts()){if(part.type!=='file')continue;const buffer=await partBuffer(part);total+=buffer.length;if(total>60*1024*1024)throw new AppError(413,'FILE_TOO_LARGE','一次上传不能超过 60 MB。');files.push({name:safeName(part.filename),mime:part.mimetype,buffer});}if(!files.length)throw new AppError(400,'EMPTY_UPLOAD','请选择要上传的文件。');const incoming=req.query.kind==='folder'?1:files.length;if(existing.length+incoming>10)throw new AppError(409,'ATTACHMENT_LIMIT','每个答案最多保存 10 个附件。');const dir=join(config.dataDir,'faq-attachments',faq.id);mkdirSync(dir,{recursive:true});if(req.query.kind==='folder'){const saved=await saveFolderZip(dir,files);const item=store.addFaqAttachment(faq.id,{name:`${safeName(req.query.folderName||files[0].name.split('/')[0]||'资料文件夹')}.zip`,storedName:saved.stored,kind:'folder',mime:'application/zip',size:saved.size});reply.code(201);return {count:1,items:[item]};}const items=[] as ReturnType<Store['addFaqAttachment']>[];for(const file of files){const kind=attachmentKind(file.name,file.mime),stored=saveBuffer(dir,file.buffer,extname(file.name).slice(1));items.push(store.addFaqAttachment(faq.id,{name:safeName(file.name),storedName:stored,kind,mime:file.mime||'application/octet-stream',size:file.buffer.length}));}reply.code(201);return {count:items.length,items};});
  app.delete<{Params:{id:string;attachmentId:string}}>(prefix+'/faqs/:id/attachments/:attachmentId',{preHandler:adminWrite,schema:{tags:['FAQ 附件'],params:{type:'object',additionalProperties:false,required:['id','attachmentId'],properties:{id:{type:'string'},attachmentId:{type:'string'}}}}},async req=>{const file=store.attachmentFile(req.params.attachmentId);if(!file||file.faq_id!==req.params.id)throw new AppError(404,'NOT_FOUND','附件不存在。');store.deleteFaqAttachment(file.id);rmSync(join(config.dataDir,'faq-attachments',file.faq_id,file.stored_name),{force:true});return {ok:true};});
  app.get<{Params:{id:string;attachmentId:string}}>(prefix+'/faqs/:id/attachments/:attachmentId/download',{preHandler:admin,schema:{tags:['FAQ 附件'],params:{type:'object',additionalProperties:false,required:['id','attachmentId'],properties:{id:{type:'string'},attachmentId:{type:'string'}}}}},async(req,reply)=>{const file=store.attachmentFile(req.params.attachmentId);if(!file||file.faq_id!==req.params.id)throw new AppError(404,'NOT_FOUND','附件不存在。');reply.header('Content-Type',file.mime).header('Content-Disposition',`attachment; filename*=UTF-8''${encodeURIComponent(file.name)}`);return reply.send(createReadStream(join(config.dataDir,'faq-attachments',file.faq_id,file.stored_name)));});
  app.get(prefix+'/rag/tree',{preHandler:admin,schema:{tags:['知识库技能']}},async()=>({folders:store.listRagFolders(),documents:store.listRagDocuments()}));
  app.post<{Body:{name:string;parentId?:string|null}}>(prefix+'/rag/folders',{preHandler:adminWrite,schema:{tags:['知识库技能'],body:{type:'object',additionalProperties:false,required:['name'],properties:{name:{type:'string',minLength:1,maxLength:80},parentId:{anyOf:[{type:'string'},{type:'null'}]}}}}},async(req,reply)=>{const result=store.saveRagFolder(req.body.name,req.body.parentId||null);reply.code(201);return result;});
  app.patch<{Params:{id:string};Body:{name:string}}>(prefix+'/rag/folders/:id',{preHandler:adminWrite,schema:{tags:['知识库技能'],params:idParams,body:{type:'object',additionalProperties:false,required:['name'],properties:{name:{type:'string',minLength:1,maxLength:80}}}}},async req=>store.renameRagFolder(req.params.id,req.body.name));
  app.delete<{Params:{id:string}}>(prefix+'/rag/folders/:id',{preHandler:adminWrite,schema:{tags:['知识库技能'],params:idParams}},async req=>store.deleteRagFolder(req.params.id));
  app.post<{Querystring:{folderId?:string}}>(prefix+'/rag/documents',{bodyLimit:210*1024*1024,preHandler:adminWrite,schema:{tags:['知识库技能'],querystring:{type:'object',additionalProperties:false,properties:{folderId:{type:'string',maxLength:100}}}}},async(req,reply)=>{const documents=[];let total=0;for await(const part of req.parts()){if(part.type!=='file')continue;if(documents.length>=20)throw new AppError(413,'DOCUMENT_LIMIT','每次最多上传 20 份资料。');const name=safeName(part.filename),ext=extname(name).toLowerCase(),image=['.png','.jpg','.jpeg','.webp'].includes(ext);if(!['.pdf','.docx','.xlsx','.xls','.png','.jpg','.jpeg','.webp'].includes(ext))throw new AppError(400,'UNSUPPORTED_DOCUMENT','仅支持图片、PDF、DOCX、XLSX、XLS 文件。');const buffer=await partBuffer(part,image?10*1024*1024:50*1024*1024);total+=buffer.length;if(total>200*1024*1024)throw new AppError(413,'FILE_TOO_LARGE','一次上传资料合计不能超过 200 MB。');const stored=saveBuffer(rag.directory,buffer,ext.slice(1));documents.push(store.createRagDocument({folderId:req.query.folderId||null,name,storedName:stored,mime:part.mimetype||'application/octet-stream',size:buffer.length}));}if(!documents.length)throw new AppError(400,'EMPTY_UPLOAD','请选择资料文件。');for(const document of documents)void rag.parse(document.id);reply.code(202);return {count:documents.length,items:documents};});
  app.get(prefix+'/rag/export.xlsx',{preHandler:admin,schema:{tags:['知识库技能']}},async(_req,reply)=>{const folders=store.listRagFolders(),documents=store.listRagDocuments(),chunks=store.listRagChunks(),graphs=documents.map(document=>store.getRagGraph(document.id)),files=documents.map(document=>{const stored=store.ragStoredName(document.id);if(!stored)throw new AppError(404,'DOCUMENT_MISSING',`资料“${document.name}”不存在。`);return {documentId:document.id,name:document.name,mime:document.mime,content:readFileSync(join(rag.directory,stored))};}),{buffer,mime}=await createRagWorkbook({folders,documents,chunks,graphs,files}),name=`知识库技能-${new Date().toISOString().slice(0,10)}.xlsx`;reply.header('Content-Type',mime).header('Content-Disposition',`attachment; filename*=UTF-8''${encodeURIComponent(name)}`);return reply.send(buffer);});
  app.get(prefix+'/rag/export-package.zip',{preHandler:admin,schema:{tags:['知识库技能']}},async(_req,reply)=>{
    const folders=store.listRagFolders(),folderNames=new Map(folders.map(folder=>[folder.id,folder.name])),documents=store.listRagDocuments(),chunks=store.listRagChunks(),graphs=documents.map(document=>store.getRagGraph(document.id)),packageFiles:{sourcePath:string;packagePath:string}[]=[],files=documents.map((document,index)=>{const stored=store.ragStoredName(document.id);if(!stored)throw new AppError(404,'DOCUMENT_MISSING',`资料“${document.name}”不存在。`);const sourcePath=join(rag.directory,stored);if(!existsSync(sourcePath))throw new AppError(404,'DOCUMENT_MISSING',`资料“${document.name}”的真实文件不存在。`);const packagePath=ragPackagePath(index+1,document.folderId?folderNames.get(document.folderId)||'未分类':'未分类',document.name);packageFiles.push({sourcePath,packagePath});return {documentId:document.id,name:document.name,mime:document.mime,content:Buffer.alloc(0),packagePath};}),{buffer}=await createRagWorkbook({folders,documents,chunks,graphs,files},{embedAttachments:false,includePackageLinks:true}),date=new Date().toISOString().slice(0,10),name=`知识库技能完整资料包-${date}.zip`,archive=createExportPackage(`知识库技能清单-${date}.xlsx`,buffer,packageFiles);reply.header('Content-Type','application/zip').header('Content-Disposition',`attachment; filename*=UTF-8''${encodeURIComponent(name)}`);return reply.send(archive);
  });
  app.delete<{Params:{id:string}}>(prefix+'/rag/documents/:id',{preHandler:adminWrite,schema:{tags:['知识库技能'],params:idParams}},async req=>{const stored=store.deleteRagDocument(req.params.id);rag.removeFile(stored);return {ok:true};});
  app.post<{Params:{id:string}}>(prefix+'/rag/documents/:id/reparse',{preHandler:adminWrite,schema:{tags:['知识库技能'],params:idParams}},async(req,reply)=>{if(!store.getRagDocument(req.params.id))throw new AppError(404,'NOT_FOUND','资料不存在。');void rag.parse(req.params.id);reply.code(202);return {ok:true};});
  app.get<{Params:{id:string}}>(prefix+'/rag/documents/:id/chunks',{preHandler:admin,schema:{tags:['知识库技能'],params:idParams}},async req=>({items:store.listRagChunks(req.params.id)}));
  app.get<{Params:{id:string}}>(prefix+'/rag/documents/:id/graph',{preHandler:admin,schema:{tags:['知识库技能'],params:idParams}},async req=>store.getRagGraph(req.params.id));
  app.get(prefix+'/rag/settings',{preHandler:admin,schema:{tags:['知识库技能']}},async()=>store.getRagSettings());
  app.patch<{Body:Omit<RagSettings,'updatedAt'>}>(prefix+'/rag/settings',{preHandler:adminWrite,schema:{tags:['知识库技能'],body:{type:'object',additionalProperties:false,required:['embeddingModel','rerankModel','parserMode','chunkSize','chunkOverlap','topK'],properties:{embeddingModel:{type:'string',maxLength:100},rerankModel:{type:'string',maxLength:100},parserMode:{enum:['local','model']},chunkSize:{type:'integer',minimum:200,maximum:2400},chunkOverlap:{type:'integer',minimum:0,maximum:1000},topK:{type:'integer',minimum:1,maximum:20}}}}},async req=>store.saveRagSettings(req.body));
  app.get<{Querystring:{type:'embedding'|'rerank'}}>(prefix+'/rag/models',{preHandler:admin,schema:{tags:['知识库技能'],querystring:{type:'object',additionalProperties:false,required:['type'],properties:{type:{enum:['embedding','rerank']}}}}},async req=>({groups:req.query.type==='embedding'?[{provider:'统一 Chunk 集合',items:[{id:'local/hash-384',name:'Hash Embedding 384D'},{id:'local/tfidf',name:'TF-IDF 768D'}]}]:[{provider:'LangChain 混合检索',items:[{id:'langchain/ensemble-rrf',name:'EnsembleRetriever 加权 RRF'}]}]}));
  app.post<{Body:{question:string;topK?:number}}>(prefix+'/rag/search',{preHandler:adminWrite,schema:{tags:['知识库技能'],body:{type:'object',additionalProperties:false,required:['question'],properties:{question:{type:'string',minLength:1,maxLength:200},topK:{type:'integer',minimum:1,maximum:20}}}}},async req=>({items:await rag.searchWithRerank(req.body.question,req.body.topK)}));
  app.post<{Body:{cases:RagEvaluationCase[]}}>(prefix+'/rag/evaluate',{
    preHandler:adminWrite,
    schema:{tags:['知识库技能'],body:{type:'object',additionalProperties:false,required:['cases'],properties:{
      cases:{type:'array',minItems:1,maxItems:50,items:{type:'object',additionalProperties:false,required:['question','expectedAnswer'],properties:{question:{type:'string',minLength:1,maxLength:200},expectedAnswer:{type:'string',minLength:1,maxLength:1500}}}},
    }}},
  },async req=>rag.evaluate(req.body.cases));
  app.get<{Querystring:ListQuery}>(prefix+'/unmatched',{preHandler:admin,schema:{tags:['未命中'],querystring:PAGE_QUERY_SCHEMA}},async req=>store.listUnmatched(req.query));
  app.get(prefix+'/unmatched/preferences',{preHandler:admin,schema:{tags:['未命中']}},async()=>store.unmatchedPreferences());
  app.patch<{Body:{offlineAutoReply:boolean}}>(prefix+'/unmatched/preferences',{preHandler:adminWrite,schema:{tags:['未命中'],body:{type:'object',additionalProperties:false,required:['offlineAutoReply'],properties:{offlineAutoReply:{type:'boolean'}}}}},async req=>store.setOfflineAutoReply(req.body.offlineAutoReply));
  app.patch<{Params:{id:string;senderId:string};Body:{name:string;qqNumber:string}}>(prefix+'/unmatched/:id/qq-students/:senderId',{preHandler:adminWrite,schema:{tags:['未命中'],params:{type:'object',additionalProperties:false,required:['id','senderId'],properties:{id:{type:'string',minLength:1,maxLength:100},senderId:{type:'string',minLength:6,maxLength:160,pattern:'^[A-Za-z0-9_-]+$'}}},body:{type:'object',additionalProperties:false,required:['name','qqNumber'],properties:{name:{type:'string',minLength:1,maxLength:80},qqNumber:{type:'string',pattern:'^[1-9][0-9]{4,11}$'}}}}},async req=>store.updateUnmatchedQqStudent(req.params.id,req.params.senderId,req.body,req.campusSession!.user.id));
  app.post<{Params:{id:string};Body:{action:'create'|'link'|'ignore';faq?:FaqInput;faqId?:string}}>(prefix+'/unmatched/:id/resolve',{
    preHandler:adminWrite,schema:{tags:['未命中'],params:idParams,body:{type:'object',additionalProperties:false,required:['action'],properties:{action:{enum:['create','link','ignore']},faq:FAQ_INPUT_SCHEMA,faqId:{type:'string',maxLength:100}}}},
  },async req=>store.resolveUnmatched(req.params.id,req.body.action,req.campusSession!.user.id,req.body.faq,req.body.faqId));
  app.post<{Body:{ids:string[];action:'ignore'|'delete'}}>(prefix+'/unmatched/batch',{preHandler:adminWrite,schema:{tags:['未命中'],body:{type:'object',additionalProperties:false,required:['ids','action'],properties:{ids:{type:'array',minItems:1,maxItems:100,uniqueItems:true,items:{type:'string',minLength:1,maxLength:100}},action:{enum:['ignore','delete']}}}}},async req=>store.batchUnmatched(req.body.ids,req.body.action,req.campusSession!.user.id));
  app.get(prefix+'/admin/developer/access',{preHandler:admin,schema:{tags:['认证']}},async req=>store.developerAccess(req.cookies.campus_session!));
  app.post<{Body:{key:string}}>(prefix+'/admin/developer/unlock',{preHandler:adminWrite,config:{rateLimit:{max:5,timeWindow:'1 minute'}},schema:{tags:['认证'],body:{type:'object',additionalProperties:false,required:['key'],properties:{key:{type:'string',minLength:8,maxLength:128}}}}},async req=>{
    if(!constantEqual(req.body.key,config.developerKey))throw new AppError(403,'INVALID_DEVELOPER_KEY','开发者密匙不正确。');
    return store.unlockDeveloper(req.cookies.campus_session!);
  });
  app.get(prefix+'/admin/account',{preHandler:admin,config:{rateLimit:{max:120,timeWindow:'1 minute'}},schema:{tags:['账户']}},async()=>{const plan=models.budget.plan();return {...plan,usage:models.status().usage};});
  app.post<{Body:{key:string}}>(prefix+'/admin/account/upgrade',{preHandler:adminWrite,config:{rateLimit:{max:5,timeWindow:'1 minute'}},schema:{tags:['账户'],body:{type:'object',additionalProperties:false,required:['key'],properties:{key:{type:'string',minLength:8,maxLength:128}}}}},async req=>{
    if(!constantEqual(req.body.key,config.developerKey))throw new AppError(403,'INVALID_UPGRADE_KEY','升级密匙不正确。');
    const plan=models.budget.upgradeToPro();return {...plan,usage:models.status().usage};
  });
  app.get(prefix+'/admin/status',{preHandler:admin,config:{rateLimit:{max:120,timeWindow:'1 minute'}},schema:{tags:['开发管理系统']}},async()=>{const botConfig=botController.status();return {...store.stats(),...publicStatus(),modelDailyLimit:config.modelDailyLimit,botConfigured:!!config.botToken,botCredentialsConfigured:botConfig.appSecretConfigured,botProcessRunning:botConfig.processRunning,qqAnswerEnabled:botConfig.processRunning&&store.servicePreference('qq_answer_enabled'),botAppId:botConfig.appId,botState:botState?.state==='connected'&&Date.now()-botState.lastSeen<45000?'connected':'offline',botLastSeen:botState?.lastSeen||null};});
  app.get(prefix+'/admin/bot/config',{preHandler:admin,schema:{tags:['QQ']}},async()=>botController.status());
  app.post<{Body:{appId:string;appSecret?:string}}>(prefix+'/admin/bot/config',{
    preHandler:adminWrite,schema:{tags:['QQ'],body:{type:'object',additionalProperties:false,required:['appId'],properties:{appId:{type:'string',pattern:'^\\d{5,20}$'},appSecret:{type:'string',minLength:0,maxLength:200}}}},
  },async req=>{store.setBotWorkspace(store.currentWorkspace());const result=botController.save(req.body);if(!result.processRunning)botState=null;if(result.appSecretConfigured)try{await botController.start();}catch(error){app.log.warn({code:error instanceof BotControlError?error.code:'BOT_AUTO_START_FAILED'},'QQ 消息接收进程自动启动未完成');}return botController.status();});
  app.post(prefix+'/admin/bot/start',{preHandler:adminWrite,config:{rateLimit:{max:5,timeWindow:'1 minute'}},schema:{tags:['QQ']}},async()=>{store.setBotWorkspace(store.currentWorkspace());const result=await botController.start();store.setServicePreference('qq_auto_start',true);store.setServicePreference('qq_answer_enabled',true);return {...result,answeringEnabled:true,message:'已恢复回答，暂停期间收到的问题将按顺序补答。'};});
  app.post(prefix+'/admin/bot/stop',{preHandler:adminWrite,config:{rateLimit:{max:5,timeWindow:'1 minute'}},schema:{tags:['QQ']}},async()=>{let status=botController.status();if(!status.processRunning&&status.appSecretConfigured){await botController.start();status=botController.status();}store.setServicePreference('qq_auto_start',true);store.setServicePreference('qq_answer_enabled',false);return {ok:true,message:'已暂停回答，QQ 消息接收仍保持在线。',processRunning:status.processRunning,answeringEnabled:false};});
  app.get(prefix+'/admin/qq/groups',{preHandler:admin,config:{rateLimit:{max:120,timeWindow:'1 minute'}},schema:{tags:['QQ 通知']}},async()=>{if(config.dbPath!==':memory:'&&!dependencies.botController)await qqGroups.sync();return {items:store.listQqGroups(botController.status().appId||undefined)};});
  app.patch<{Params:{id:string};Body:{label:string;enabled:boolean;groupNumber?:string}}>(prefix+'/admin/qq/groups/:id',{preHandler:adminWrite,schema:{tags:['QQ 通知'],params:idParams,body:{type:'object',additionalProperties:false,required:['label','enabled'],properties:{label:{type:'string',minLength:1,maxLength:100},enabled:{type:'boolean'},groupNumber:{type:'string',maxLength:15,pattern:'^([1-9][0-9]{4,14})?$'}}}}},async req=>store.updateQqGroup(req.params.id,req.body,req.campusSession!.user.id));
  app.delete<{Params:{id:string}}>(prefix+'/admin/qq/groups/:id',{preHandler:adminWrite,schema:{tags:['QQ 通知'],params:idParams}},async req=>store.deleteQqGroup(req.params.id,req.campusSession!.user.id));
  app.get(prefix+'/admin/materials/categories',{preHandler:admin,schema:{tags:['资料整理']}},async()=>({items:store.listMaterialCategories()}));
  app.post<{Body:{name:string}}>(prefix+'/admin/materials/categories',{preHandler:adminWrite,schema:{tags:['资料整理'],body:{type:'object',additionalProperties:false,required:['name'],properties:{name:{type:'string',minLength:1,maxLength:60}}}}},async(req,reply)=>{reply.code(201);return store.createMaterialCategory(req.body.name);});
  app.patch<{Params:{id:string};Body:{name:string}}>(prefix+'/admin/materials/categories/:id',{preHandler:adminWrite,schema:{tags:['资料整理'],params:idParams,body:{type:'object',additionalProperties:false,required:['name'],properties:{name:{type:'string',minLength:1,maxLength:60}}}}},async req=>store.renameMaterialCategory(req.params.id,req.body.name));
  app.delete<{Params:{id:string}}>(prefix+'/admin/materials/categories/:id',{preHandler:adminWrite,schema:{tags:['资料整理'],params:idParams}},async req=>store.deleteMaterialCategory(req.params.id));
  app.get<{Querystring:{q?:string;status?:MaterialStatus;categoryId?:string;page?:number;pageSize?:number}}>(prefix+'/admin/materials',{preHandler:admin,schema:{tags:['资料整理'],querystring:{type:'object',additionalProperties:false,properties:{q:{type:'string',maxLength:200},status:{enum:['pending_confirm','pending_archive','archived']},categoryId:{type:'string',maxLength:100},page:{type:'integer',minimum:1,default:1},pageSize:{type:'integer',minimum:1,maximum:100,default:10}}}}},async req=>store.listMaterialItems(req.query));
  app.patch<{Params:{id:string};Body:{categoryId:string|null}}>(prefix+'/admin/materials/:id',{preHandler:adminWrite,schema:{tags:['资料整理'],params:idParams,body:{type:'object',additionalProperties:false,required:['categoryId'],properties:{categoryId:{anyOf:[{type:'string',minLength:1,maxLength:100},{type:'null'}]}}}}},async req=>store.updateMaterialItem(req.params.id,req.body.categoryId));
  app.get<{Params:{id:string}}>(prefix+'/admin/materials/:id/download',{preHandler:admin,schema:{tags:['资料整理'],params:idParams}},async(req,reply)=>{const file=store.materialItemFile(req.params.id);if(!file)throw new AppError(404,'NOT_FOUND','资料不存在。');const path=join(materialDirectory,file.stored_name);if(!existsSync(path))throw new AppError(404,'FILE_MISSING','资料文件不存在。');reply.header('Content-Type',file.mime).header('Content-Length',String(file.size)).header('Content-Disposition',`attachment; filename*=UTF-8''${encodeURIComponent(file.name)}`);return reply.send(createReadStream(path));});
  app.get<{Querystring:{ids:string}}>(prefix+'/admin/materials/download.zip',{preHandler:admin,schema:{tags:['资料整理'],querystring:{type:'object',additionalProperties:false,required:['ids'],properties:{ids:{type:'string',minLength:8,maxLength:10000}}}}},async(req,reply)=>{const ids=[...new Set(req.query.ids.split(',').filter(id=>/^[A-Za-z0-9_-]{8,100}$/.test(id)))].slice(0,100);if(!ids.length)throw new AppError(400,'INVALID_SELECTION','请选择资料。');const files=ids.map(id=>store.materialItemFile(id)).filter(Boolean) as NonNullable<ReturnType<Store['materialItemFile']>>[];if(!files.length)throw new AppError(404,'NOT_FOUND','资料不存在。');const used=new Map<string,number>(),entries=files.map((file,index)=>{const count=(used.get(file.name)||0)+1;used.set(file.name,count);const name=count===1?file.name:`${String(index+1).padStart(2,'0')}-${file.name}`;return {sourcePath:join(materialDirectory,file.stored_name),packagePath:safeName(name)};});reply.header('Content-Type','application/zip').header('Content-Disposition',`attachment; filename*=UTF-8''${encodeURIComponent('资料整理-'+new Date().toISOString().slice(0,10)+'.zip')}`);return reply.send(createFileArchive(entries));});
  app.delete<{Params:{id:string}}>(prefix+'/admin/materials/:id',{preHandler:adminWrite,schema:{tags:['资料整理'],params:idParams}},async req=>{const rows=store.deleteMaterialItems([req.params.id]);for(const row of rows)rmSync(join(materialDirectory,row.stored_name),{force:true});return {ok:true,id:req.params.id};});
  app.delete<{Body:{ids:string[]}}>(prefix+'/admin/materials',{preHandler:adminWrite,schema:{tags:['资料整理'],body:{type:'object',additionalProperties:false,required:['ids'],properties:{ids:{type:'array',minItems:1,maxItems:100,uniqueItems:true,items:{type:'string',minLength:8,maxLength:100}}}}}},async req=>{const rows=store.deleteMaterialItems(req.body.ids);for(const row of rows)rmSync(join(materialDirectory,row.stored_name),{force:true});return {ok:true,count:rows.length};});
  app.get<{Querystring:{limit?:number}}>(prefix+'/admin/notifications',{preHandler:admin,config:{rateLimit:{max:120,timeWindow:'1 minute'}},schema:{tags:['QQ 通知'],querystring:{type:'object',additionalProperties:false,properties:{limit:{type:'integer',minimum:1,maximum:50,default:20}}}}},async req=>({items:store.listNotifications(req.query.limit)}));
  app.delete<{Params:{id:string}}>(prefix+'/admin/notifications/:id',{preHandler:adminWrite,schema:{tags:['QQ 通知'],params:idParams}},async req=>store.deleteNotification(req.params.id,req.campusSession!.user.id));
  app.post(prefix+'/admin/notifications',{bodyLimit:70*1024*1024,preHandler:adminWrite,config:{rateLimit:{max:10,timeWindow:'1 minute'}},schema:{tags:['QQ 通知']}},async(req,reply)=>{
    if(!req.isMultipart()){const result=store.createNotification(req.body as NotificationInput,req.campusSession!.user.id,botController.status().appId||undefined);reply.code(202);return result;}
    let payloadText='';const files:{name:string;mime:string;buffer:Buffer}[]=[],folderFiles:{name:string;mime:string;buffer:Buffer}[]=[];let total=0;
    for await(const part of req.parts()){if(part.type==='field'){if(part.fieldname==='payload')payloadText=String(part.value);continue;}const buffer=await partBuffer(part);total+=buffer.length;if(total>60*1024*1024)throw new AppError(413,'FILE_TOO_LARGE','通知附件合计不能超过 60 MB。');const item={name:safeName(part.filename),mime:part.mimetype||'application/octet-stream',buffer};if(part.fieldname==='folder')folderFiles.push(item);else if(part.fieldname==='files')files.push(item);else throw new AppError(400,'INVALID_UPLOAD','通知附件字段无效。');}
    let input:NotificationInput;try{input=JSON.parse(payloadText) as NotificationInput;}catch{throw new AppError(400,'INVALID_NOTIFICATION','通知内容格式无效。');}
    if(files.length+(folderFiles.length?1:0)>10)throw new AppError(400,'ATTACHMENT_LIMIT','每条通知最多添加 10 个附件。');
    const directory=join(config.dataDir,'notification-attachments');mkdirSync(directory,{recursive:true});const saved:{name:string;storedName:string;kind:ReturnType<typeof notificationAttachmentKind>|'folder';mime:string;size:number}[]=[];
    try{for(const file of files){const kind=notificationAttachmentKind(file.name,file.mime),storedName=saveBuffer(directory,file.buffer,extname(file.name).slice(1));saved.push({name:file.name,storedName,kind,mime:file.mime,size:file.buffer.length});}if(folderFiles.length){const archive=await saveFolderZip(directory,folderFiles),root=safeName(folderFiles[0].name.split('/')[0]||'资料文件夹');saved.push({name:`${root}.zip`,storedName:archive.stored,kind:'folder',mime:'application/zip',size:archive.size});}const result=store.createNotification(input,req.campusSession!.user.id,botController.status().appId||undefined,saved);for(const item of saved)if(!store.notificationAttachmentStored(item.storedName))rmSync(join(directory,item.storedName),{force:true});reply.code(202);return result;}catch(error){for(const item of saved)if(!store.notificationAttachmentStored(item.storedName))rmSync(join(directory,item.storedName),{force:true});throw error;}
  });
  const providerParams={type:'object',required:['provider'],properties:{provider:{enum:['deepseek','zhipu']}}};
  app.get(prefix+'/admin/models',{preHandler:admin,config:{rateLimit:{max:120,timeWindow:'1 minute'}},schema:{tags:['模型']}},async()=>models.status());
  app.post<{Params:{provider:TextModelProvider};Body:{apiKey?:string}}>(prefix+'/admin/models/:provider/connect',{preHandler:developerWrite,config:{rateLimit:{max:5,timeWindow:'1 minute'}},schema:{tags:['模型'],params:providerParams,body:{type:'object',additionalProperties:false,properties:{apiKey:{type:'string',maxLength:512}}}}},async req=>{const result=await models.connect(req.params.provider,req.body.apiKey);store.setServicePreference(`${req.params.provider}_auto_start`,true);return result;});
  app.post<{Params:{provider:TextModelProvider}}>(prefix+'/admin/models/:provider/disconnect',{preHandler:developerWrite,schema:{tags:['模型'],params:providerParams}},async req=>{models.settings.connected(req.params.provider,false);store.setServicePreference(`${req.params.provider}_auto_start`,false);return models.status();});
  app.post<{Body:{provider:TextModelProvider}}>(prefix+'/admin/models/select',{preHandler:adminWrite,schema:{tags:['模型'],body:{type:'object',additionalProperties:false,required:['provider'],properties:{provider:{enum:['deepseek','zhipu']}}}}},async req=>{models.settings.select(req.body.provider);return models.status();});
  app.post<{Body:AnswerInput}>(prefix+'/admin/answer/test',{bodyLimit:8500000,preHandler:adminWrite,schema:{tags:['模型'],body:ANSWER_INPUT_SCHEMA,response:{200:ANSWER_RESPONSE_SCHEMA}}},req=>answers.answer(req.body,'web'));
  app.get(prefix+'/admin/openapi',{preHandler:admin,schema:{hide:true}},async()=>app.swagger());
  app.addHook('onClose',async()=>{models.close();if(!dependencies.store)store.close();});
  await app.ready();
  if(config.dbPath!==':memory:'&&!dependencies.botController&&botController.status().appSecretConfigured)void botController.start().catch(error=>app.log.warn({code:error instanceof BotControlError?error.code:'BOT_AUTO_START_FAILED'},'QQ 消息接收进程自动启动未完成'));
  return {app,store,answers,config,models};
}
