import { useEffect,useState,type FormEvent } from 'react';
import { Badge,Button,Checkbox,Dialog,DialogSurface,DialogBody,DialogTitle,DialogContent,DialogActions,Field,Input,Select,Spinner,Switch,Textarea } from '@fluentui/react-components';
import { ArrowClockwise,Check,Link as LinkIcon,MagnifyingGlass,PencilSimple,Plus,Trash,UserCircle,X } from '@phosphor-icons/react';
import type { Faq,FaqInput,PageResult,Unmatched,UnmatchedPreferences,UnmatchedQqStudent,UnmatchedType } from '@campus/contracts';
import { CATEGORIES } from '@campus/contracts';
import { api,ApiError,messageOf } from '../api';
import { dateTime,Empty,FaqState,Loading,Notice,PageTitle,Pagination,Retry,useData } from '../ui';
const emptyFaq: FaqInput={question:'',answer:'',keywords:[],category:CATEGORIES[0],status:'disabled',confirmed:false};
function FaqEditor({initial,open,onClose,onSave}:{initial:Partial<Faq>|null;open:boolean;onClose:()=>void;onSave:(value:FaqInput)=>Promise<void>}) {
  const current=initial||{};
  const [form,setForm]=useState<FaqInput>(emptyFaq),[keywords,setKeywords]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
  useEffect(()=>{if(open){setForm({question:initial?.question||'',answer:initial?.answer||'',keywords:initial?.keywords||[],category:initial?.category||emptyFaq.category,status:initial?.status||'disabled',confirmed:false});setKeywords((initial?.keywords||[]).join('，'));setError('');}},[open,initial?.id,initial?.question,initial?.version]);
  const change=<K extends keyof FaqInput>(key:K,value:FaqInput[K])=>setForm(old=>({...old,[key]:value}));
  async function submit(event:FormEvent){event.preventDefault();setBusy(true);setError('');try{await onSave({...form,keywords:keywords.split(/[,，\n]/).map(x=>x.trim()).filter(Boolean)});onClose();}catch(error){setError(error instanceof ApiError&&error.status===409?`${error.message} 请关闭窗口、刷新列表后再编辑；可先复制当前内容。`:messageOf(error));}finally{setBusy(false);}}
  return <Dialog open={open} onOpenChange={(_,data)=>{if(!data.open&&!busy)onClose();}}><DialogSurface className="faq-dialog"><DialogBody><DialogTitle action={<Button appearance="subtle" aria-label="关闭编辑" icon={<X/>} disabled={busy} onClick={onClose}/>}>{current.id?'编辑知识条目':'新增知识条目'}</DialogTitle><DialogContent><p className="muted dialog-intro">使用学生熟悉的问法，给出可以直接执行的办理指引。</p><form id="faq-form" onSubmit={submit} className="editor-form">{error&&<Notice>{error}</Notice>}<Field label="标准问题" required><Input value={form.question} maxLength={200} onChange={(_,d)=>change('question',d.value)} required/></Field><Field label="标准答案" required hint={`${form.answer.length}/1500 · 不填写个人信息，具体时间以学校通知为准。`}><Textarea value={form.answer} maxLength={1500} rows={5} resize="vertical" onChange={(_,d)=>change('answer',d.value)} required/></Field><Field label="匹配关键词" required hint="使用具体事项名称，以中文逗号分隔，例如：申请缓考，缓考手续。"><Input value={keywords} onChange={(_,d)=>setKeywords(d.value)} required/></Field><div className="form-pair"><Field label="分类"><Select value={form.category} onChange={(_,d)=>change('category',d.value)}>{CATEGORIES.map(x=><option key={x}>{x}</option>)}</Select></Field><Field label="公开状态"><Select value={form.status} onChange={(_,d)=>change('status',d.value as FaqInput['status'])}><option value="disabled">停用，保存为待核实内容</option><option value="active">启用，向学生开放</option></Select></Field></div><Checkbox checked={form.confirmed} onChange={(_,d)=>change('confirmed',d.checked===true)} label="我已核实答案准确、适用于本校，可以向学生公开。"/>{current.isDemo&&<Notice intent="warning">保存修改后，此条目将移出演示标记。请核实内容后再启用。</Notice>}</form></DialogContent><DialogActions><Button onClick={onClose} disabled={busy}>取消</Button><Button form="faq-form" type="submit" appearance="primary" disabled={busy||(form.status==='active'&&!form.confirmed)} icon={busy?<Spinner size="tiny"/>:<Check/>}>{busy?'正在保存':'保存条目'}</Button></DialogActions></DialogBody></DialogSurface></Dialog>;
}
export function Questions(){const [q,setQ]=useState(''),[search,setSearch]=useState(''),[status,setStatus]=useState(''),[category,setCategory]=useState(''),[page,setPage]=useState(1),[revision,setRevision]=useState(0),[editor,setEditor]=useState<Partial<Faq>|null>(null),[notice,setNotice]=useState('');const params=new URLSearchParams({q:search,status,category,page:String(page),pageSize:'10'});const {data,error,loading}=useData<PageResult<Faq>>('/faqs?'+params,revision);
  async function save(value:FaqInput){await api(editor?.id?`/faqs/${editor.id}`:'/faqs',{method:editor?.id?'PATCH':'POST',body:editor?.id?{...value,version:editor.version}:value});setNotice('知识条目已保存，网页与 QQ 将使用最新内容。');setRevision(x=>x+1);}
  return <div className="admin-page"><PageTitle eyebrow="KNOWLEDGE LIBRARY" title="知识库" actions={<Button appearance="primary" icon={<Plus/>} onClick={()=>setEditor({})}>新增条目</Button>}/>{notice&&<Notice intent="success">{notice}</Notice>}<section className="panel table-panel"><form className="table-toolbar" onSubmit={e=>{e.preventDefault();setSearch(q);setPage(1);}}><Field label="搜索知识"><Input contentBefore={<MagnifyingGlass/>} placeholder="搜索问题或答案" value={q} onChange={(_,d)=>setQ(d.value)}/></Field><Field label="分类"><Select value={category} onChange={(_,d)=>{setCategory(d.value);setPage(1);}}><option value="">全部分类</option>{CATEGORIES.map(x=><option key={x}>{x}</option>)}</Select></Field><Field label="状态"><Select value={status} onChange={(_,d)=>{setStatus(d.value);setPage(1);}}><option value="">全部状态</option><option value="active">已启用</option><option value="disabled">已停用</option></Select></Field><Button type="submit">查询</Button><Button type="button" aria-label="刷新列表" icon={<ArrowClockwise/>} onClick={()=>setRevision(x=>x+1)}/></form>
    {error?<Retry error={error} onRetry={()=>setRevision(x=>x+1)}/>:loading?<Loading/>:data?.items.length?<><div className="table-scroll"><table className="data-table"><thead><tr><th>标准问题 / 关键词</th><th>分类</th><th>状态</th><th>最近更新</th><th className="table-action">操作</th></tr></thead><tbody>{data.items.map(item=><tr key={item.id}><td><strong>{item.question}</strong><div className="keyword-list">{item.keywords.slice(0,3).map(k=><span key={k}>{k}</span>)}{item.keywords.length>3&&<span>+{item.keywords.length-3}</span>}</div></td><td>{item.category}</td><td><FaqState status={item.status} isDemo={item.isDemo}/></td><td className="date-cell">{dateTime(item.updatedAt)}<small>版本 {item.version}</small></td><td><Button appearance="subtle" icon={<PencilSimple/>} aria-label={`编辑 ${item.question}`} onClick={()=>setEditor(item)}>编辑</Button></td></tr>)}</tbody></table></div><Pagination page={page} pageSize={10} total={data.total} onChange={setPage}/></>:<Empty title="没有找到相关知识" description="调整筛选条件，或新增第一条已核实的标准答案。" action={<Button icon={<Plus/>} onClick={()=>setEditor({})}>新增条目</Button>}/>}</section><FaqEditor initial={editor} open={editor!==null} onClose={()=>setEditor(null)} onSave={save}/></div>;
}
function StudentIdentityDialog({selection,onClose,onSaved}:{selection:{item:Unmatched;source:UnmatchedQqStudent}|null;onClose:()=>void;onSaved:()=>void}){const [name,setName]=useState(''),[qqNumber,setQqNumber]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');useEffect(()=>{if(selection){setName(selection.source.name||'');setQqNumber(selection.source.qqNumber||'');setError('');}},[selection?.item.id,selection?.source.id]);async function submit(event:FormEvent){event.preventDefault();if(!selection)return;setBusy(true);setError('');try{await api(`/unmatched/${selection.item.id}/qq-students/${selection.source.id}`,{method:'PATCH',body:{name,qqNumber}});onSaved();onClose();}catch(e){setError(messageOf(e));}finally{setBusy(false);}}return <Dialog open={selection!==null} onOpenChange={(_,d)=>{if(!d.open&&!busy)onClose();}}><DialogSurface><DialogBody><DialogTitle>核实学生 QQ 资料</DialogTitle><DialogContent><p className="muted">QQ 官方机器人通常不会提供数字 QQ 号。请根据班级名单或向学生核实后补录。</p>{error&&<Notice>{error}</Notice>}<form id="student-identity-form" className="editor-form" onSubmit={submit}><Field label="QQ 昵称" required><Input value={name} maxLength={80} onChange={(_,d)=>setName(d.value)} required/></Field><Field label="QQ号" required><Input value={qqNumber} inputMode="numeric" maxLength={12} placeholder="例如：3556762784" onChange={(_,d)=>setQqNumber(d.value.replace(/\D/g,''))} required/></Field></form></DialogContent><DialogActions><Button disabled={busy} onClick={onClose}>取消</Button><Button form="student-identity-form" type="submit" appearance="primary" disabled={busy||!name.trim()||!/^[1-9]\d{4,11}$/.test(qqNumber)}>{busy?'正在保存':'保存资料'}</Button></DialogActions></DialogBody></DialogSurface></Dialog>;}
export function UnmatchedPage(){
  const [status,setStatus]=useState('pending'),[type,setType]=useState<UnmatchedType>('manual'),[q,setQ]=useState(''),[search,setSearch]=useState(''),[page,setPage]=useState(1),[revision,setRevision]=useState(0),[notice,setNotice]=useState(''),[errorAction,setErrorAction]=useState(''),[create,setCreate]=useState<Unmatched|null>(null),[link,setLink]=useState<Unmatched|null>(null),[student,setStudent]=useState<{item:Unmatched;source:UnmatchedQqStudent}|null>(null),[selected,setSelected]=useState<string[]>([]),[confirm,setConfirm]=useState<{action:'ignore'|'delete';ids:string[]}|null>(null),[busy,setBusy]=useState(false),[preferenceBusy,setPreferenceBusy]=useState(false);
  const {data,error,loading}=useData<PageResult<Unmatched>>('/unmatched?'+new URLSearchParams({q:search,status,unmatchedType:type,page:String(page),pageSize:'10'}),revision),preferences=useData<UnmatchedPreferences>('/unmatched/preferences',revision),items=data?.items||[];
  useEffect(()=>setSelected(old=>old.filter(id=>items.some(item=>item.id===id))),[data]);
  const allSelected=items.length>0&&items.every(item=>selected.includes(item.id)),selectedItems=items.filter(item=>selected.includes(item.id)),canIgnore=selectedItems.length>0&&selectedItems.every(item=>item.status==='pending');
  async function resolve(item:Unmatched,body:unknown){const result=await api<{queuedReplies:number}>(`/unmatched/${item.id}/resolve`,{method:'POST',body});setRevision(x=>x+1);setNotice(result.queuedReplies>0?`问题已处理，已加入 ${result.queuedReplies} 名学生的 QQ 回发队列。`:'问题已处理；该记录没有可回发的 QQ 学生来源。');}
  async function runBatch(){if(!confirm)return;setBusy(true);setErrorAction('');try{const result=await api<{count:number}>('/unmatched/batch',{method:'POST',body:confirm});setNotice(confirm.action==='ignore'?`已忽略 ${result.count} 条问题。`:`已删除 ${result.count} 条问题记录。`);setSelected([]);setConfirm(null);setRevision(x=>x+1);}catch(e){setErrorAction(messageOf(e));}finally{setBusy(false);}}
  async function toggleOffline(enabled:boolean){setPreferenceBusy(true);try{await api('/unmatched/preferences',{method:'PATCH',body:{offlineAutoReply:enabled}});setNotice(enabled?'恢复连线后将按顺序自动补答。':'离线问题自动补答已关闭。');setRevision(x=>x+1);}catch(e){setErrorAction(messageOf(e));}finally{setPreferenceBusy(false);}}
  const labels:Record<UnmatchedType,string>={manual:'转人工处理',unrelated:'无关问题',offline:'未答问题'};
  const changeView=()=>{setPage(1);setSelected([]);setNotice('');setErrorAction('');};
  return <div className="admin-page unmatched-page">
    <PageTitle eyebrow="QUESTIONS TO REVIEW" title="待解答问题" actions={<Button icon={<ArrowClockwise/>} onClick={()=>setRevision(x=>x+1)}>刷新</Button>}/>
    {notice&&<Notice intent="success">{notice}</Notice>}{errorAction&&<Notice>{errorAction}</Notice>}
    <div className="unmatched-category-bar" role="tablist" aria-label="问题类别">{(Object.keys(labels) as UnmatchedType[]).map(value=><Button key={value} role="tab" aria-selected={type===value} appearance={type===value?'primary':'subtle'} onClick={()=>{setType(value);changeView();}}>{labels[value]}</Button>)}{type==='offline'&&<div className="offline-reply-toggle"><span>连线后逐个自动回复</span><Switch aria-label="连线后逐个自动回复" checked={preferences.data?.offlineAutoReply??true} disabled={preferenceBusy||preferences.loading} onChange={(_,value)=>void toggleOffline(value.checked)}/></div>}</div>
    <section className="panel table-panel">
      <form className="table-toolbar" onSubmit={e=>{e.preventDefault();setSearch(q);changeView();}}><Field label="搜索问题"><Input contentBefore={<MagnifyingGlass/>} placeholder="输入关键词" value={q} onChange={(_,value)=>setQ(value.value)}/></Field><Field label="处理状态"><Select value={status} onChange={(_,value)=>{setStatus(value.value);changeView();}}><option value="pending">待处理</option><option value="resolved">已解决</option><option value="ignored">已忽略</option><option value="">全部</option></Select></Field><Button type="submit">查询</Button></form>
      {items.length>0&&<div className="unmatched-batch-bar"><Checkbox checked={allSelected} label="选择本页" onChange={(_,value)=>setSelected(value.checked===true?items.map(item=>item.id):[])}/><span>已选择 {selected.length} 条</span><Button size="small" disabled={!canIgnore||busy} onClick={()=>setConfirm({action:'ignore',ids:selected})}>批量忽略</Button><Button size="small" appearance="subtle" icon={<Trash/>} disabled={!selected.length||busy} onClick={()=>setConfirm({action:'delete',ids:selected})}>批量删除</Button></div>}
      {error?<Retry error={error} onRetry={()=>setRevision(x=>x+1)}/>:loading?<Loading/>:items.length?<><div className="unmatched-list" tabIndex={0} role="region" aria-label="待解答问题滚动区域">{items.map(item=><article className={`unmatched-item ${selected.includes(item.id)?'selected':''}`} key={item.id}><Checkbox checked={selected.includes(item.id)} aria-label={`选择 ${item.question}`} onChange={(_,value)=>setSelected(old=>value.checked===true?[...new Set([...old,item.id])]:old.filter(id=>id!==item.id))}/><div className="unmatched-item-content"><div className="unmatched-meta"><Badge appearance="tint" color={item.status==='pending'?'warning':'subtle'}>{item.status==='pending'?'待处理':item.status==='resolved'?'已解决':'已忽略'}</Badge><Badge appearance="outline">{labels[item.type]}</Badge><span>{item.reason==='ambiguous'?'含义不明确':item.type==='offline'?'离线期间未答':'知识库未命中'}</span><span>{dateTime(item.lastSeen)}</span></div><h3>{item.question}</h3><p>网页 {item.webCount} 次 · QQ {item.qqCount} 次</p>{item.qqStudents.length>0&&<div className="qq-student-list" aria-label="咨询学生信息">{item.qqStudents.map(source=><div className="qq-student" key={source.id}><UserCircle size={28}/><span><strong>{source.name||'QQ 昵称待核实'}</strong><small>{source.qqNumber?`QQ号：${source.qqNumber} · `:'QQ号待核实 · '}本问题咨询 {source.questionCount} 次</small></span><Button size="small" appearance="subtle" onClick={()=>setStudent({item,source})}>{source.qqNumber?'修改资料':'补录QQ号'}</Button></div>)}</div>}</div><div className="unmatched-actions">{item.status==='pending'&&item.type!=='offline'&&<><Button appearance="primary" icon={<Plus/>} onClick={()=>setCreate(item)}>补充解答</Button><Button icon={<LinkIcon/>} onClick={()=>setLink(item)}>关联知识</Button></>}{item.status==='pending'&&<Button appearance="subtle" onClick={()=>setConfirm({action:'ignore',ids:[item.id]})}>忽略</Button>}<Button appearance="subtle" icon={<Trash/>} onClick={()=>setConfirm({action:'delete',ids:[item.id]})}>删除</Button></div></article>)}</div><Pagination page={page} pageSize={10} total={data?.total||0} onChange={value=>{setPage(value);setSelected([]);}}/></>:<Empty title={`${labels[type]}中暂时没有问题`}/>}
    </section>
    <FaqEditor initial={create?{question:create.question}:null} open={create!==null} onClose={()=>setCreate(null)} onSave={value=>create?resolve(create,{action:'create',faq:value}):Promise.resolve()}/><LinkDialog item={link} onClose={()=>setLink(null)} onSave={id=>link?resolve(link,{action:'link',faqId:id}):Promise.resolve()}/>
    <StudentIdentityDialog selection={student} onClose={()=>setStudent(null)} onSaved={()=>{setNotice('学生 QQ 资料已保存。');setRevision(x=>x+1);}}/>
    <Dialog open={confirm!==null} onOpenChange={(_,value)=>{if(!value.open&&!busy)setConfirm(null);}}><DialogSurface><DialogBody><DialogTitle>{confirm?.action==='delete'?'删除问题记录？':'忽略所选问题？'}</DialogTitle><DialogContent><p>{confirm?.action==='delete'?`将永久删除所选 ${confirm.ids.length} 条问题及其学生来源记录，此操作无法撤销。`:`所选 ${confirm?.ids.length||0} 条问题将移入已忽略列表，之后仍可查询。`}</p>{errorAction&&<Notice>{errorAction}</Notice>}</DialogContent><DialogActions><Button disabled={busy} onClick={()=>setConfirm(null)}>取消</Button><Button className={confirm?.action==='delete'?'destructive-action':undefined} appearance="primary" disabled={busy} onClick={()=>void runBatch()}>{busy?'正在处理':confirm?.action==='delete'?'确认删除':'确认忽略'}</Button></DialogActions></DialogBody></DialogSurface></Dialog>
  </div>;
}
function LinkDialog({item,onClose,onSave}:{item:Unmatched|null;onClose:()=>void;onSave:(id:string)=>Promise<void>}){const [q,setQ]=useState(''),[id,setId]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');useEffect(()=>{if(item){setQ('');setId('');setError('');}},[item?.id]);const {data,error:loadError}=useData<PageResult<Faq>>('/faqs?'+new URLSearchParams({status:'active',q,pageSize:'100'}));return <Dialog open={item!==null} onOpenChange={(_,d)=>{if(!d.open&&!busy)onClose();}}><DialogSurface><DialogBody><DialogTitle>关联已有知识</DialogTitle><DialogContent><p className="muted">{item?.question}</p><p className="muted">归类此记录不会自动增加匹配关键词。若需命中相同问法，请随后编辑该知识条目。</p>{(error||loadError)&&<Notice>{error||loadError}</Notice>}<Field label="查找标准问题"><Input value={q} onChange={(_,d)=>{setQ(d.value);setId('');}}/></Field><Field label="选择已启用的条目"><Select value={id} onChange={(_,d)=>setId(d.value)}><option value="">请选择</option>{data?.items.map(f=><option key={f.id} value={f.id}>{f.question}</option>)}</Select></Field></DialogContent><DialogActions><Button disabled={busy} onClick={onClose}>取消</Button><Button appearance="primary" disabled={!id||busy} onClick={async()=>{setBusy(true);setError('');try{await onSave(id);onClose();}catch(e){setError(messageOf(e));}finally{setBusy(false);}}}>确认关联</Button></DialogActions></DialogBody></DialogSurface></Dialog>;}
