import { useEffect,useMemo,useRef,useState,type FormEvent } from 'react';
import { Link } from 'react-router-dom';
import { Badge,Button,Dialog,DialogActions,DialogBody,DialogContent,DialogSurface,DialogTitle,Field,Input,ProgressBar,Select } from '@fluentui/react-components';
import { Archive,ArrowClockwise,ArrowLeft,DownloadSimple,File,FileArrowUp,Folder,Gear,Graph,HardDrives,ListMagnifyingGlass,MagnifyingGlass,PencilSimple,Plus,SortAscending,Trash } from '@phosphor-icons/react';
import type { RagChunk,RagDocument,RagFolder,RagGraph,RagSettings } from '@campus/contracts';
import { api,apiDownload,apiUpload,messageOf } from '../api';
import { Empty,Loading,Notice,Pagination,Retry,useData } from '../ui';

type RagTree={folders:RagFolder[];documents:RagDocument[]};
type ModelGroup={provider:string;items:{id:string;name:string}[]};
const PAGE_SIZE=10;

function ModelSelect({type,value,onChange}:{type:'embedding'|'rerank';value:string;onChange:(value:string)=>void}){
  const [groups,setGroups]=useState<ModelGroup[]|null>(null),[error,setError]=useState('');
  async function load(){if(groups)return;try{setGroups((await api<{groups:ModelGroup[]}>(`/rag/models?type=${type}`)).groups);}catch(cause){setError(messageOf(cause));}}
  return <Field label={type==='embedding'?'向量算法':'混合检索'} validationMessage={error}><Select value={value} onFocus={()=>void load()} onChange={(_,data)=>onChange(data.value)}>{!groups&&<option value={value}>{value||'展开加载算法'}</option>}{groups?.map(group=><optgroup key={group.provider} label={group.provider}>{group.items.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</optgroup>)}</Select></Field>;
}

export function KnowledgeSkills(){
  const [revision,setRevision]=useState(0),[folderId,setFolderId]=useState(''),[newFolder,setNewFolder]=useState(''),[notice,setNotice]=useState(''),[actionError,setActionError]=useState(''),[settings,setSettings]=useState<RagSettings|null>(null),[modelsOpen,setModelsOpen]=useState(false),[fileQuery,setFileQuery]=useState(''),[sort,setSort]=useState<'az'|'za'|'newest'>('az'),[page,setPage]=useState(1),[uploading,setUploading]=useState(false),[exporting,setExporting]=useState(false),[chunks,setChunks]=useState<{document:RagDocument;items:RagChunk[]}|null>(null),[graph,setGraph]=useState<RagGraph|null>(null),[renameTarget,setRenameTarget]=useState<RagFolder|null>(null),[renameName,setRenameName]=useState(''),fileRef=useRef<HTMLInputElement|null>(null);
  const {data,error,loading}=useData<RagTree>('/rag/tree',revision),settingsData=useData<RagSettings>('/rag/settings',revision);
  useEffect(()=>{if(settingsData.data&&!settings)setSettings(settingsData.data);},[settingsData.data,settings]);
  useEffect(()=>{if(!data?.documents.some(item=>item.status==='pending'||item.status==='parsing'))return;const id=window.setInterval(()=>setRevision(value=>value+1),1800);return()=>window.clearInterval(id);},[data?.documents]);
  useEffect(()=>setPage(1),[folderId,fileQuery,sort]);
  const folders=useMemo(()=>[...(data?.folders||[])].sort((a,b)=>a.name.localeCompare(b.name,'zh-CN',{numeric:true,sensitivity:'base'})),[data?.folders]);
  const documents=useMemo(()=>{const query=fileQuery.trim().toLocaleLowerCase(),items=(data?.documents||[]).filter(item=>(item.folderId||'')===folderId&&(!query||item.name.toLocaleLowerCase().includes(query)));return items.sort((a,b)=>sort==='newest'?b.updatedAt-a.updatedAt:sort==='za'?b.name.localeCompare(a.name,'zh-CN',{numeric:true,sensitivity:'base'}):a.name.localeCompare(b.name,'zh-CN',{numeric:true,sensitivity:'base'}));},[data?.documents,folderId,fileQuery,sort]);
  const pageCount=Math.max(1,Math.ceil(documents.length/PAGE_SIZE)),currentPage=Math.min(page,pageCount),visibleDocuments=documents.slice((currentPage-1)*PAGE_SIZE,currentPage*PAGE_SIZE);
  useEffect(()=>{if(page>pageCount)setPage(pageCount);},[page,pageCount]);

  async function upload(files:File[]){if(!files.length)return;setUploading(true);setActionError('');try{const body=new FormData();for(const file of files)body.append('file',file,file.name);const result=await apiUpload<{count:number}>(`/rag/documents${folderId?`?folderId=${encodeURIComponent(folderId)}`:''}`,body);setNotice(`${result.count} 份资料已进入上传进度。`);setSort('newest');setPage(1);setRevision(value=>value+1);}catch(cause){setActionError(messageOf(cause));}finally{setUploading(false);if(fileRef.current)fileRef.current.value='';}}
  async function exportAll(){setExporting(true);setActionError('');try{const blob=await apiDownload('/rag/export.xlsx'),url=URL.createObjectURL(blob),anchor=document.createElement('a');anchor.href=url;anchor.download=`知识库技能-${new Date().toISOString().slice(0,10)}.xlsx`;anchor.click();URL.revokeObjectURL(url);setNotice('知识库资料已导出，真实原始文件已嵌入 Excel，可双击带文件名的资料条打开。');}catch(cause){setActionError(messageOf(cause));}finally{setExporting(false);}}
  async function exportPackage(){setExporting(true);setActionError('');try{const blob=await apiDownload('/rag/export-package.zip'),url=URL.createObjectURL(blob),anchor=document.createElement('a');anchor.href=url;anchor.download=`知识库技能完整资料包-${new Date().toISOString().slice(0,10)}.zip`;anchor.click();URL.revokeObjectURL(url);setNotice('完整资料包已导出，解压后可从 Excel 清单直接打开真实资料。');}catch(cause){setActionError(messageOf(cause));}finally{setExporting(false);}}
  async function addFolder(event:FormEvent){event.preventDefault();try{await api('/rag/folders',{method:'POST',body:{name:newFolder}});setNewFolder('');setRevision(value=>value+1);}catch(cause){setActionError(messageOf(cause));}}
  function beginRename(folder:RagFolder){setRenameTarget(folder);setRenameName(folder.name);setActionError('');}
  async function renameFolder(event:FormEvent){event.preventDefault();if(!renameTarget||!renameName.trim())return;try{const saved=await api<RagFolder>(`/rag/folders/${renameTarget.id}`,{method:'PATCH',body:{name:renameName}});setRenameTarget(null);setNotice(`目录已重命名为“${saved.name}”。`);setRevision(value=>value+1);}catch(cause){setActionError(messageOf(cause));}}
  async function showChunks(document:RagDocument){try{const result=await api<{items:RagChunk[]}>(`/rag/documents/${document.id}/chunks`);setChunks({document,items:result.items});}catch(cause){setActionError(messageOf(cause));}}
  async function showGraph(document:RagDocument){try{setGraph(await api<RagGraph>(`/rag/documents/${document.id}/graph`));}catch(cause){setActionError(messageOf(cause));}}
  async function saveSettings(){if(!settings)return;try{setSettings(await api<RagSettings>('/rag/settings',{method:'PATCH',body:{embeddingModel:settings.embeddingModel,rerankModel:settings.rerankModel,parserMode:settings.parserMode,chunkSize:settings.chunkSize,chunkOverlap:settings.chunkOverlap,topK:settings.topK}}));setModelsOpen(false);setNotice('检索配置已保存。');}catch(cause){setActionError(messageOf(cause));}}
  const graphLabels=new Map(graph?.nodes.map(node=>[node.id,node.label])||[]);

  return <div className="admin-page rag-page">
    <header className="rag-page-header"><div className="rag-title-group"><Link className="knowledge-back" to="/admin/knowledge" aria-label="返回知识库" title="返回知识库"><ArrowLeft size={22}/></Link><h1>知识库技能</h1></div><div className="rag-page-actions"><Button icon={<Gear/>} onClick={()=>setModelsOpen(true)}>检索配置</Button><Button icon={<DownloadSimple/>} disabled={exporting} onClick={()=>void exportAll()}>{exporting?'正在处理':'一键导出 Excel'}</Button><Button icon={<Archive/>} disabled={exporting} onClick={()=>void exportPackage()}>{exporting?'正在处理':'导出完整资料包'}</Button><Button appearance="primary" icon={<FileArrowUp/>} disabled={uploading} onClick={()=>fileRef.current?.click()}>{uploading?'正在上传':'上传资料'}</Button><input ref={fileRef} hidden type="file" multiple accept=".pdf,.docx,.xlsx,.xls,.png,.jpg,.jpeg,.webp" onChange={event=>event.target.files&&void upload([...event.target.files])}/></div></header>
    {notice&&<Notice intent="success">{notice}</Notice>}{actionError&&<Notice>{actionError}</Notice>}
    {error?<Retry error={error} onRetry={()=>setRevision(value=>value+1)}/>:loading?<Loading/>:<div className="rag-workspace">
      <aside className="panel rag-folders"><div className="rag-section-heading"><h2>目录结构</h2><Badge appearance="outline">{folders.length}</Badge></div><div className="rag-folder-scroll"><div className={!folderId?'rag-folder-row selected':'rag-folder-row'}><button className="folder-select" onClick={()=>setFolderId('')}><HardDrives/><span>所有目录</span><small>{data?.documents.length||0}</small></button></div>{folders.map(folder=><div className={folderId===folder.id?'rag-folder-row selected':'rag-folder-row'} key={folder.id}><button className="folder-select" onClick={()=>setFolderId(folder.id)}><Folder/><span>{folder.name}</span><small>{data?.documents.filter(item=>item.folderId===folder.id).length}</small></button><Button appearance="subtle" size="small" icon={<PencilSimple/>} aria-label={`编辑目录 ${folder.name}`} onClick={()=>beginRename(folder)}/></div>)}</div><form onSubmit={addFolder} className="new-folder"><Input size="small" value={newFolder} placeholder="新目录名称" aria-label="新目录名称" onChange={(_,value)=>setNewFolder(value.value)}/><Button size="small" type="submit" icon={<Plus/>} disabled={!newFolder.trim()} aria-label="新增目录"/></form></aside>
      <section className="panel rag-documents"><div className="rag-section-heading"><h2>上传进度</h2><div className="rag-heading-actions"><Badge appearance="outline">{documents.length} 个资料</Badge><Button size="small" icon={<ArrowClockwise/>} onClick={()=>setRevision(value=>value+1)}>刷新</Button></div></div><div className="document-toolbar"><Input contentBefore={<MagnifyingGlass/>} value={fileQuery} placeholder="搜索已上传文件" aria-label="搜索已上传文件" onChange={(_,value)=>setFileQuery(value.value)}/><Select aria-label="资料排序" value={sort} onChange={(_,value)=>setSort(value.value as typeof sort)}><option value="az">A 到 Z</option><option value="za">Z 到 A</option><option value="newest">最新上传</option></Select><SortAscending/></div>
        {documents.length?<><div className="document-list-scroll"><div className="document-list">{visibleDocuments.map(document=><article key={document.id}><div className="document-icon"><File/></div><div className="document-main"><div><strong>{document.name}</strong><Badge appearance="tint" color={document.status==='ready'?'success':document.status==='failed'?'danger':'informative'}>{document.status==='ready'?'图谱已就绪':document.status==='failed'?'处理失败':document.status==='parsing'?'构建图谱中':'等待处理'}</Badge></div><ProgressBar thickness="medium" value={document.progress/100}/><small>{(document.size/1024/1024).toFixed(2)} MB，{document.chunkCount} Chunks，{document.tokenCount.toLocaleString()} Tokens，{document.graphNodeCount} 节点 / {document.graphEdgeCount} 关系</small>{document.error&&<span className="inline-error">{document.error}</span>}</div><div className="document-actions"><Button appearance="subtle" icon={<Graph/>} disabled={!document.graphNodeCount} onClick={()=>void showGraph(document)}>知识图谱</Button><Button appearance="subtle" icon={<ListMagnifyingGlass/>} disabled={!document.chunkCount} onClick={()=>void showChunks(document)}>切片</Button><Button appearance="subtle" icon={<ArrowClockwise/>} onClick={async()=>{await api(`/rag/documents/${document.id}/reparse`,{method:'POST'});setRevision(value=>value+1);}}>重解析</Button><Button appearance="subtle" icon={<Trash/>} aria-label={`删除 ${document.name}`} onClick={async()=>{await api(`/rag/documents/${document.id}`,{method:'DELETE'});setRevision(value=>value+1);}}/></div></article>)}</div></div><Pagination page={currentPage} pageSize={PAGE_SIZE} total={documents.length} onChange={setPage}/></>:<Empty title={fileQuery?'没有找到匹配文件':'还没有上传资料'} action={!fileQuery?<Button icon={<FileArrowUp/>} onClick={()=>fileRef.current?.click()}>上传资料</Button>:undefined}/>}
      </section>
    </div>}
    <Dialog open={!!renameTarget} onOpenChange={(_,value)=>!value.open&&setRenameTarget(null)}><DialogSurface><form onSubmit={renameFolder}><DialogBody><DialogTitle>编辑目录名称</DialogTitle><DialogContent><Field label="目录名称"><Input autoFocus value={renameName} onChange={(_,value)=>setRenameName(value.value)}/></Field></DialogContent><DialogActions><Button onClick={()=>setRenameTarget(null)}>取消</Button><Button appearance="primary" type="submit" disabled={!renameName.trim()}>保存</Button></DialogActions></DialogBody></form></DialogSurface></Dialog>
    <Dialog open={modelsOpen} onOpenChange={(_,value)=>!value.open&&setModelsOpen(false)}><DialogSurface><DialogBody><DialogTitle>检索与解析配置</DialogTitle><DialogContent>{settings&&<div className="editor-form"><ModelSelect type="embedding" value={settings.embeddingModel} onChange={value=>setSettings({...settings,embeddingModel:value})}/><ModelSelect type="rerank" value={settings.rerankModel} onChange={value=>setSettings({...settings,rerankModel:value})}/><Field label="切片大小（字符）"><Input type="number" value={String(settings.chunkSize)} onChange={(_,value)=>setSettings({...settings,chunkSize:Number(value.value)})}/></Field><Field label="切片重叠（字符）"><Input type="number" value={String(settings.chunkOverlap)} onChange={(_,value)=>setSettings({...settings,chunkOverlap:Number(value.value)})}/></Field><Field label="Top K"><Input type="number" value={String(settings.topK)} onChange={(_,value)=>setSettings({...settings,topK:Number(value.value)})}/></Field></div>}</DialogContent><DialogActions><Button onClick={()=>setModelsOpen(false)}>取消</Button><Button appearance="primary" onClick={()=>void saveSettings()}>保存配置</Button></DialogActions></DialogBody></DialogSurface></Dialog>
    <Dialog open={!!chunks} onOpenChange={(_,value)=>!value.open&&setChunks(null)}><DialogSurface className="chunk-dialog"><DialogBody><DialogTitle>{chunks?.document.name} · Chunk 切片</DialogTitle><DialogContent><div className="chunk-list">{chunks?.items.map(item=><article key={item.id}><span>Chunk {item.position+1} · {item.tokenCount} Tokens</span><p>{item.content}</p></article>)}</div></DialogContent><DialogActions><Button onClick={()=>setChunks(null)}>关闭</Button></DialogActions></DialogBody></DialogSurface></Dialog>
    <Dialog open={!!graph} onOpenChange={(_,value)=>!value.open&&setGraph(null)}><DialogSurface className="chunk-dialog"><DialogBody><DialogTitle>{graph?.document.name} · 知识图谱</DialogTitle><DialogContent><div className="graph-summary"><div><strong>{graph?.nodes.length||0}</strong><span>知识节点</span></div><div><strong>{graph?.edges.length||0}</strong><span>节点关系</span></div></div><div className="graph-node-list">{graph?.nodes.map(node=><article key={node.id}><Badge appearance="tint">{node.type}</Badge><div><strong>{node.label}</strong><p>{node.description}</p></div></article>)}</div>{graph?.edges.length?<div className="graph-edge-list"><h3>关系</h3>{graph.edges.map(edge=><p key={edge.id}>{graphLabels.get(edge.sourceId)||'节点'} <span>{edge.relation}</span> {graphLabels.get(edge.targetId)||'节点'}</p>)}</div>:null}</DialogContent><DialogActions><Button onClick={()=>setGraph(null)}>关闭</Button></DialogActions></DialogBody></DialogSurface></Dialog>
  </div>;
}
