import { useState,type FormEvent } from 'react';
import { Button,Field,Input,Spinner,Tab,TabList } from '@fluentui/react-components';
import { Key,ArrowRight,ShieldCheck,UserPlus } from '@phosphor-icons/react';
import { Navigate,useLocation,useNavigate } from 'react-router-dom';
import type { SessionResult } from '@campus/contracts';
import { useAuth } from '../main';
import { api,messageOf } from '../api';
import { Notice } from '../ui';
export function Login(){const {session,setSession}=useAuth(),navigate=useNavigate(),location=useLocation();const [mode,setMode]=useState<'login'|'register'>('login'),[username,setUsername]=useState(''),[password,setPassword]=useState(''),[registrationCode,setRegistrationCode]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  async function submit(event:FormEvent){event.preventDefault();setBusy(true);setError('');try{const result=await api<SessionResult>(mode==='register'?'/auth/register':'/auth/login',{method:'POST',body:mode==='register'?{username,password,registrationCode}:{username,password}});setSession(result);const from=location.state?.from,target=result.user.role==='developer'?'/developer/accounts':typeof from==='string'&&from.startsWith('/admin')?from:'/admin';navigate(target,{replace:true});}catch(error){setError(messageOf(error));}finally{setBusy(false);}}
  if(session)return <Navigate to={session.user.role==='developer'?'/developer/accounts':'/admin'} replace/>;
  return <div className="login-layout"><section className="login-story"><span className="eyebrow">FOR ACADEMIC STAFF</span><h1>把经验整理好，<br/>让解答更从容。</h1><p>维护一份清楚、准确的教务知识库，<br/>通过 QQ 为学生提供准确的解答。</p><div className="login-principles"><div><BookNumber n="01"/><span>核实内容，再向学生开放</span></div><div><BookNumber n="02"/><span>收集未命中，持续完善知识库</span></div><div><BookNumber n="03"/><span>账号数据相互隔离</span></div></div><span className="login-signature">校园教务小助手</span></section><section className="login-panel"><div className="icon-tile">{mode==='login'?<Key size={25} weight="duotone"/>:<UserPlus size={25} weight="duotone"/>}</div><h2>{mode==='login'?'登录工作台':'注册老师账号'}</h2><TabList className="login-tabs" selectedValue={mode} onTabSelect={(_,data)=>{setMode(data.value as 'login'|'register');setError('');}}><Tab value="login">登录</Tab><Tab value="register">注册</Tab></TabList><form onSubmit={submit}>{error&&<Notice>{error}</Notice>}<Field label="账号名称" required><Input autoComplete="username" name="username" value={username} maxLength={40} onChange={(_,data)=>setUsername(data.value)} required/></Field><Field label="口令" hint={mode==='register'?'至少 12 个字符':undefined} required><Input type="password" autoComplete={mode==='register'?'new-password':'current-password'} name="password" value={password} maxLength={128} onChange={(_,data)=>setPassword(data.value)} required/></Field>{mode==='register'&&<Field label="注册码" required><Input type="password" autoComplete="off" name="registration-code" value={registrationCode} maxLength={32} onChange={(_,data)=>setRegistrationCode(data.value)} required/></Field>}<Button appearance="primary" size="large" type="submit" disabled={busy||!username||!password||(mode==='register'&&(!registrationCode||password.length<12))} icon={busy?<Spinner size="tiny"/>:mode==='register'?<UserPlus/>:<ArrowRight/>} iconPosition="after">{busy?'正在提交':mode==='register'?'完成注册':'进入工作台'}</Button></form><p className="login-help"><ShieldCheck size={18}/>忘记账号或口令时，请使用开发者账号登录查看已注册账号或重置口令。</p></section></div>;
}
function BookNumber({n}:{n:string}){return <span className="book-number">{n}</span>;}
