import { useEffect,useMemo,useState } from 'react';
import { Badge,Button,Checkbox,Dialog,DialogActions,DialogBody,DialogContent,DialogSurface,DialogTitle,Field,Input,Select,Spinner } from '@fluentui/react-components';
import { ArrowClockwise,Check,DownloadSimple,File,FolderSimplePlus,MagnifyingGlass,PencilSimple,Trash,X } from '@phosphor-icons/react';
import type { MaterialCategory,MaterialItem,MaterialStatus,PageResult } from '@campus/contracts';
import { api,apiDownload,messageOf } from '../api';
import { Empty,Loading,Notice,PageTitle,Pagination,Retry,dateTime,useData } from '../ui';

const statusText:Record<MaterialStatus,string>={pending_confirm:'待确认',pending_archive:'待归档',archived:'已归档'};
const SYSTEM_CATEGORY='无关类别';
const statusColor=(status:MaterialStatus)=>status==='archived'?'success':status==='pending_confirm'?'warning':'subtle';
const fileSize=(bytes:number)=>bytes<1024?`${bytes} B`:bytes<1024*1024?`${(bytes/1024).toFixed(1)} KB`:`${(bytes/1024/1024).toFixed(1)} MB`;
function saveBlob(blob:Blob,name:string){const url=URL.createObjectURL(blob),anchor=document.createElement('a');anchor.href=url;anchor.download=name;document.body.append(anchor);anchor.click();anchor.remove();setTimeout(()=>URL.revokeObjectURL(url),2000);}

export function Materials(){
  const [page,setPage]=useState(1),[q,setQ]=useState(''),[status,setStatus]=useState(''),[categoryId,setCategoryId]=useState(''),[revision,setRevision]=useState(0),[selected,setSelected]=useState<string[]>([]),[notice,setNotice]=useState<{ok:boolean;text:string}|null>(null),[busy,setBusy]=useState('');
  const [manageCategories,setManageCategories]=useState(false),[deleteTargets,setDeleteTargets]=useState<string[]>([]);
  const query=useMemo(()=>new URLSearchParams({page:String(page),pageSize:'10',...(q.trim()?{q:q.trim()}:{}),...(status?{status}:{}),...(categoryId?{categoryId}:{})}).toString(),[page,q,status,categoryId]);
  const data=useData<PageResult<MaterialItem>>('/admin/materials?'+query,revision),categories=useData<{items:MaterialCategory[]}>('/admin/materials/categories',revision);
  const items=data.data?.items||[],allSelected=items.length>0&&items.every(item=>selected.includes(item.id));
  useEffect(()=>{setSelected(current=>current.filter(id=>items.some(item=>item.id===id)));},[data.data]);
  useEffect(()=>{const timer=setInterval(()=>setRevision(value=>value+1),12000);return()=>clearInterval(timer);},[]);
  const refresh=()=>setRevision(value=>value+1);
  function toggleAll(){setSelected(allSelected?[]:items.map(item=>item.id));}
  async function archive(item:MaterialItem,nextCategoryId:string){if(!nextCategoryId){setNotice({ok:false,text:'请先选择归档类别。'});return;}setBusy(item.id);setNotice(null);try{await api(`/admin/materials/${item.id}`,{method:'PATCH',body:{categoryId:nextCategoryId}});setNotice({ok:true,text:'资料已确认归档。'});refresh();}catch(error){setNotice({ok:false,text:messageOf(error)});}finally{setBusy('');}}
  async function downloadOne(item:MaterialItem){setBusy('download-'+item.id);setNotice(null);try{saveBlob(await apiDownload(`/admin/materials/${item.id}/download`),item.name);}catch(error){setNotice({ok:false,text:messageOf(error)});}finally{setBusy('');}}
  async function downloadBatch(){if(!selected.length)return;setBusy('batch-download');setNotice(null);try{saveBlob(await apiDownload('/admin/materials/download.zip?ids='+encodeURIComponent(selected.join(','))),`资料整理-${new Date().toISOString().slice(0,10)}.zip`);}catch(error){setNotice({ok:false,text:messageOf(error)});}finally{setBusy('');}}
  async function remove(){if(!deleteTargets.length)return;setBusy('delete');setNotice(null);try{if(deleteTargets.length===1)await api('/admin/materials/'+deleteTargets[0],{method:'DELETE'});else await api('/admin/materials',{method:'DELETE',body:{ids:deleteTargets}});const count=deleteTargets.length;setSelected([]);setDeleteTargets([]);setNotice({ok:true,text:`已删除 ${count} 份资料。`});refresh();}catch(error){setNotice({ok:false,text:messageOf(error)});}finally{setBusy('');}}
  return <div className="admin-page materials-page"><PageTitle eyebrow="MATERIAL INBOX" title="资料整理" actions={<><Button icon={<FolderSimplePlus/>} onClick={()=>setManageCategories(true)}>类别管理</Button><Button icon={<ArrowClockwise/>} onClick={refresh}>刷新</Button></>}/>{notice&&<Notice intent={notice.ok?'success':'error'}>{notice.text}</Notice>}
    <section className="panel table-panel materials-panel"><div className="materials-toolbar"><Field label="搜索资料"><Input value={q} contentBefore={<MagnifyingGlass/>} placeholder="输入文件名" onChange={(_,value)=>{setQ(value.value);setPage(1);}}/></Field><Field label="状态"><Select value={status} onChange={event=>{setStatus(event.target.value);setPage(1);}}><option value="">全部状态</option><option value="pending_confirm">待确认</option><option value="pending_archive">待归档</option><option value="archived">已归档</option></Select></Field><Field label="类别"><Select value={categoryId} onChange={event=>{setCategoryId(event.target.value);setPage(1);}}><option value="">全部类别</option>{categories.data?.items.map(category=><option key={category.id} value={category.id}>{category.name}</option>)}</Select></Field><div className="materials-batch-actions"><Button icon={busy==='batch-download'?<Spinner size="tiny"/>:<DownloadSimple/>} disabled={!selected.length||!!busy} onClick={()=>void downloadBatch()}>批量下载</Button><Button icon={<Trash/>} disabled={!selected.length||!!busy} onClick={()=>setDeleteTargets(selected)}>批量删除</Button></div></div>
      {data.error?<Retry error={data.error} onRetry={refresh}/>:data.loading&&!data.data?<Loading/>:items.length?<><div className="materials-table-scroll" tabIndex={0} role="region" aria-label="资料列表滚动区域"><table className="materials-table"><thead><tr><th><Checkbox checked={allSelected} aria-label="选择本页资料" onChange={toggleAll}/></th><th>资料</th><th>分类</th><th>状态</th><th>接收时间</th><th>操作</th></tr></thead><tbody>{items.map(item=><MaterialRow key={item.id} item={item} categories={categories.data?.items||[]} checked={selected.includes(item.id)} busy={busy===item.id||busy==='download-'+item.id} onChecked={checked=>setSelected(current=>checked?[...new Set([...current,item.id])]:current.filter(id=>id!==item.id))} onArchive={value=>void archive(item,value)} onDownload={()=>void downloadOne(item)} onDelete={()=>setDeleteTargets([item.id])}/>)}</tbody></table></div><Pagination page={page} total={data.data?.total||0} pageSize={10} onChange={setPage}/></>:<Empty title="暂无待整理资料"/>}
    </section>
    <CategoryManager open={manageCategories} categories={categories.data?.items||[]} onClose={()=>setManageCategories(false)} onChanged={refresh}/>
    <Dialog open={deleteTargets.length>0} onOpenChange={(_,value)=>{if(!value.open&&busy!=='delete')setDeleteTargets([]);}}><DialogSurface><DialogBody><DialogTitle>删除资料</DialogTitle><DialogContent>确认删除选中的 {deleteTargets.length} 份资料？真实文件也会一并删除。</DialogContent><DialogActions><Button disabled={busy==='delete'} onClick={()=>setDeleteTargets([])}>取消</Button><Button appearance="primary" icon={busy==='delete'?<Spinner size="tiny"/>:<Trash/>} disabled={busy==='delete'} onClick={()=>void remove()}>确认删除</Button></DialogActions></DialogBody></DialogSurface></Dialog>
  </div>;
}

function MaterialRow({item,categories,checked,busy,onChecked,onArchive,onDownload,onDelete}:{item:MaterialItem;categories:MaterialCategory[];checked:boolean;busy:boolean;onChecked:(value:boolean)=>void;onArchive:(categoryId:string)=>void;onDownload:()=>void;onDelete:()=>void}){
  const [category,setCategory]=useState(item.categoryId||'');useEffect(()=>setCategory(item.categoryId||''),[item.categoryId]);
  return <tr><td><Checkbox checked={checked} aria-label={`选择 ${item.name}`} onChange={(_,value)=>onChecked(value.checked===true)}/></td><td><div className="material-name"><span><File weight="duotone"/></span><div><strong>{item.name}</strong><small>{fileSize(item.size)}</small></div></div></td><td><Select aria-label={`${item.name}的归档类别`} value={category} onChange={event=>setCategory(event.target.value)}>{categories.map(entry=><option key={entry.id} value={entry.id}>{entry.name}</option>)}</Select></td><td><Badge appearance="tint" color={statusColor(item.status)}>{statusText[item.status]}</Badge></td><td>{dateTime(item.createdAt)}</td><td><div className="material-actions"><Button size="small" appearance="subtle" icon={busy?<Spinner size="tiny"/>:<Check/>} disabled={busy||!category} onClick={()=>onArchive(category)}>确认</Button><Button size="small" appearance="subtle" icon={<DownloadSimple/>} disabled={busy} onClick={onDownload}>下载</Button><Button size="small" appearance="subtle" icon={<Trash/>} disabled={busy} onClick={onDelete}>删除</Button></div></td></tr>;
}

function CategoryManager({open,categories,onClose,onChanged}:{open:boolean;categories:MaterialCategory[];onClose:()=>void;onChanged:()=>void}){
  const [name,setName]=useState(''),[editing,setEditing]=useState<string|null>(null),[draft,setDraft]=useState(''),[busy,setBusy]=useState(''),[error,setError]=useState('');
  async function create(){setBusy('create');setError('');try{await api('/admin/materials/categories',{method:'POST',body:{name}});setName('');onChanged();}catch(reason){setError(messageOf(reason));}finally{setBusy('');}}
  async function save(id:string){setBusy(id);setError('');try{await api('/admin/materials/categories/'+id,{method:'PATCH',body:{name:draft}});setEditing(null);onChanged();}catch(reason){setError(messageOf(reason));}finally{setBusy('');}}
  async function remove(id:string){setBusy(id);setError('');try{await api('/admin/materials/categories/'+id,{method:'DELETE'});onChanged();}catch(reason){setError(messageOf(reason));}finally{setBusy('');}}
  return <Dialog open={open} onOpenChange={(_,value)=>{if(!value.open)onClose();}}><DialogSurface><DialogBody><DialogTitle action={<Button appearance="subtle" aria-label="关闭类别管理" icon={<X/>} onClick={onClose}/>}>类别管理</DialogTitle><DialogContent><div className="material-category-create"><Input value={name} maxLength={60} placeholder="输入新类别" onChange={(_,value)=>setName(value.value)}/><Button appearance="primary" icon={busy==='create'?<Spinner size="tiny"/>:<FolderSimplePlus/>} disabled={!name.trim()||!!busy} onClick={()=>void create()}>新增</Button></div>{error&&<Notice>{error}</Notice>}<div className="material-category-list">{categories.map(category=>{const system=category.name===SYSTEM_CATEGORY;return <div key={category.id}>{editing===category.id?<Input value={draft} maxLength={60} aria-label={`编辑 ${category.name}`} onChange={(_,value)=>setDraft(value.value)}/>:<span>{category.name}{system&&<Badge appearance="tint">系统</Badge>}</span>}<div>{editing===category.id?<><Button appearance="subtle" size="small" icon={<Check/>} disabled={!draft.trim()||!!busy} onClick={()=>void save(category.id)}>保存</Button><Button appearance="subtle" size="small" onClick={()=>setEditing(null)}>取消</Button></>:!system&&<><Button appearance="subtle" size="small" icon={<PencilSimple/>} onClick={()=>{setEditing(category.id);setDraft(category.name);}}>编辑</Button><Button appearance="subtle" size="small" icon={<Trash/>} disabled={busy===category.id} onClick={()=>void remove(category.id)}>删除</Button></>}</div></div>;})}</div></DialogContent></DialogBody></DialogSurface></Dialog>;
}
