import { useEffect,useMemo,useRef,useState } from 'react';
import { Badge,Button,Checkbox,Dialog,DialogActions,DialogBody,DialogContent,DialogSurface,DialogTitle,Dropdown,Option,Field,Input,Spinner,Textarea } from '@fluentui/react-components';
import { ArrowClockwise,At,Check,File,FolderOpen,Megaphone,PencilSimple,PaperPlaneTilt,Paperclip,UsersThree,X,Copy,NotePencil,Trash } from '@phosphor-icons/react';
import type { NotificationRecord,QqGroup } from '@campus/contracts';
import { api,apiUpload,messageOf } from '../api';
import { Empty,Loading,Notice,PageTitle,Retry,dateTime,useData } from '../ui';
const selectable=(group:QqGroup)=>group.enabled&&group.available!==false;
const identity=(group:QqGroup)=>`${group.label} · ${group.groupNumber?'群号 '+group.groupNumber:'群号待补录'}`;

export function Notifications(){
  const [revision,setRevision]=useState(0),[historyRevision,setHistoryRevision]=useState(0),[manage,setManage]=useState(false);
  const groups=useData<{items:QqGroup[]}>('/admin/qq/groups',revision),history=useData<{items:NotificationRecord[]}>('/admin/notifications?limit=50',revision+historyRevision);
  const [selected,setSelected]=useState<string[]>([]),[title,setTitle]=useState(''),[content,setContent]=useState(''),[files,setFiles]=useState<File[]>([]),[folderFiles,setFolderFiles]=useState<File[]>([]),[sending,setSending]=useState(false),[notice,setNotice]=useState<{ok:boolean;text:string}|null>(null);
  const [deleting,setDeleting]=useState<NotificationRecord|null>(null),[deleteBusy,setDeleteBusy]=useState(false),[deleteError,setDeleteError]=useState('');
  const [deletingGroup,setDeletingGroup]=useState<QqGroup|null>(null),[groupDeleteBusy,setGroupDeleteBusy]=useState(false),[groupDeleteError,setGroupDeleteError]=useState('');
  const deleteLock=useRef(false),folderRef=useRef<HTMLInputElement|null>(null),fileRef=useRef<HTMLInputElement|null>(null);
  const submission=useRef({payload:'',requestId:''});
  useEffect(()=>{folderRef.current?.setAttribute('webkitdirectory','');folderRef.current?.setAttribute('directory','');},[]);
  useEffect(()=>{const timer=setInterval(()=>setHistoryRevision(x=>x+1),5000),groupTimer=setInterval(()=>setRevision(x=>x+1),15000);return()=>{clearInterval(timer);clearInterval(groupTimer);};},[]);
  const items=groups.data?.items||[],enabled=items.filter(selectable);
  const selectedGroups=useMemo(()=>(groups.data?.items||[]).filter(group=>selectable(group)&&selected.includes(group.id)),[groups.data,selected]);
  useEffect(()=>{if(groups.data)setSelected(current=>current.filter(id=>groups.data!.items.some(group=>selectable(group)&&group.id===id)));},[groups.data]);
  function select(ids:string[]){if(ids.length>20){setNotice({ok:false,text:'每次最多选择 20 个群聊。'});return;}setSelected(ids.filter(id=>enabled.some(group=>group.id===id)));}
  const refresh=()=>setRevision(x=>x+1);
  async function send(event:React.FormEvent){event.preventDefault();setSending(true);setNotice(null);try{const attachmentKey=[...files.map(x=>`${x.name}:${x.size}`),...(folderFiles.length?[`folder:${folderFiles.map(x=>(x as File&{webkitRelativePath?:string}).webkitRelativePath||x.name).join('|')}`]:[])],payload=JSON.stringify({title,content,groupIds:[...selected].sort(),attachmentKey});if(submission.current.payload!==payload)submission.current={payload,requestId:crypto.randomUUID()};const body=new FormData();body.append('payload',JSON.stringify({requestId:submission.current.requestId,title,content,groupIds:selected}));for(const file of files)body.append('files',file,file.name);for(const file of folderFiles)body.append('folder',file,(file as File&{webkitRelativePath?:string}).webkitRelativePath||file.name);const result=await apiUpload<NotificationRecord>('/admin/notifications',body);submission.current={payload:'',requestId:''};setTitle('');setContent('');setSelected([]);setFiles([]);setFolderFiles([]);if(fileRef.current)fileRef.current.value='';if(folderRef.current)folderRef.current.value='';setNotice({ok:true,text:`通知已进入发送队列，共 ${result.targetCount} 个群聊。`});refresh();}catch(error){setNotice({ok:false,text:messageOf(error)});}finally{setSending(false);}}
  function pickFiles(list:File[]){const unique=[...files,...list].filter((file,index,all)=>all.findIndex(x=>x.name===file.name&&x.size===file.size)===index);if(unique.length+(folderFiles.length?1:0)>10){setNotice({ok:false,text:'每条通知最多添加 10 个附件，文件夹按 1 个附件计算。'});return;}setFiles(unique);submission.current={payload:'',requestId:''};}
  function pickFolder(list:File[]){if(files.length+1>10){setNotice({ok:false,text:'每条通知最多添加 10 个附件，文件夹按 1 个附件计算。'});return;}setFolderFiles(list);submission.current={payload:'',requestId:''};}
  async function removeRecord(){
    if(!deleting||deleteLock.current)return;deleteLock.current=true;setDeleteBusy(true);setDeleteError('');
    try{await api('/admin/notifications/'+encodeURIComponent(deleting.id),{method:'DELETE'});history.setData(current=>current?{items:current.items.filter(item=>item.id!==deleting.id)}:current);setDeleting(null);setNotice({ok:true,text:'发送记录已删除。'});setHistoryRevision(x=>x+1);}
    catch(error){setDeleteError(messageOf(error));}
    finally{deleteLock.current=false;setDeleteBusy(false);}
  }
  async function removeGroup(){if(!deletingGroup||groupDeleteBusy)return;setGroupDeleteBusy(true);setGroupDeleteError('');try{await api('/admin/qq/groups/'+encodeURIComponent(deletingGroup.id),{method:'DELETE'});setSelected(current=>current.filter(id=>id!==deletingGroup.id));setDeletingGroup(null);setNotice({ok:true,text:'群聊已从通知列表删除。'});refresh();}catch(error){setGroupDeleteError(messageOf(error));}finally{setGroupDeleteBusy(false);}}
  const permissionError=history.data?.items.some(item=>item.targets.some(target=>target.lastError?.includes('40034105')));
  function editAgain(item:NotificationRecord){setTitle(item.title);setContent(item.content);setSelected(item.targets.filter(target=>target.status==='failed'&&enabled.some(group=>group.id===target.groupId)).map(target=>target.groupId));submission.current={payload:'',requestId:''};setNotice({ok:true,text:'通知已放回编辑区，请处理失败原因并核对群聊后发送。'});window.scrollTo({top:0,behavior:'instant'});}
  return <div className="admin-page notification-page"><PageTitle eyebrow="GROUP NOTIFICATIONS" title="一键发送通知" actions={<Button icon={<ArrowClockwise/>} onClick={refresh}>刷新状态</Button>}/>{notice&&<Notice intent={notice.ok?'success':'error'}>{notice.text}</Notice>}
    <div className="notification-layout">
      <form className="panel notification-composer" onSubmit={send}><div className="panel-title"><div><h2>编写通知</h2></div><Megaphone size={25} weight="duotone"/></div>
        <Field label="通知标题" required hint={`${title.length} / 80`}><Input value={title} maxLength={80} onChange={(_,data)=>setTitle(data.value)} placeholder="例如：本周选课提醒" required/></Field>
        <Field label="通知内容" required hint={`${content.length} / 1500`}><Textarea value={content} maxLength={1500} rows={8} resize="vertical" onChange={(_,data)=>setContent(data.value)} placeholder="填写时间、地点、办理要求和咨询方式" required/></Field>
        <div className="notification-attachment-picker"><div className="notification-attachment-heading"><strong>通知附件</strong><Badge appearance="outline">{files.length+(folderFiles.length?1:0)} / 10</Badge></div><div className="notification-attachment-actions"><Button type="button" icon={<Paperclip/>} onClick={()=>fileRef.current?.click()}>选择资料</Button><input ref={fileRef} hidden type="file" multiple accept="image/*,video/*,.pdf,.doc,.docx,.xls,.xlsx,.mp4,.mov,.avi,.mkv,.webm,.wmv,.m4v" onChange={event=>pickFiles([...event.target.files||[]])}/><Button type="button" icon={<FolderOpen/>} onClick={()=>folderRef.current?.click()}>选择文件夹</Button><input ref={folderRef} hidden type="file" multiple onChange={event=>pickFolder([...event.target.files||[]])}/></div>{(files.length>0||folderFiles.length>0)&&<div className="notification-attachment-list">{files.map((file,index)=><div key={`${file.name}-${file.size}`}><File/><span>{file.name}</span><Button type="button" appearance="subtle" size="small" aria-label={`移除 ${file.name}`} icon={<X/>} onClick={()=>setFiles(files.filter((_,i)=>i!==index))}/></div>)}{folderFiles.length>0&&<div><FolderOpen/><span>{(folderFiles[0] as File&{webkitRelativePath?:string}).webkitRelativePath?.split('/')[0]||'资料文件夹'}（{folderFiles.length} 个文件）</span><Button type="button" appearance="subtle" size="small" aria-label="移除文件夹" icon={<X/>} onClick={()=>setFolderFiles([])}/></div>}</div>}</div>
        <div className="notification-preview"><span>发送预览</span><div className="notification-recipient-lock"><At/>全体成员</div><strong>{title?`【${title}】`:'【通知标题】'}</strong><p>{content||'通知正文将在这里预览。'}</p></div>
        <Button className="notification-send" appearance="primary" size="large" type="submit" icon={sending?<Spinner size="tiny"/>:<PaperPlaneTilt/>} disabled={sending||!title.trim()||!content.trim()||!selected.length}>{sending?'正在提交':selected.length?`发送到 ${selected.length} 个群`:'请先选择群聊'}</Button>
      </form>
      <div className="notification-right-column">
        <section className="panel group-selector" aria-label="通知群聊"><div className="panel-title"><div><h2>通知群聊</h2></div><UsersThree size={25} weight="duotone"/></div>
          {groups.error?<Retry error={groups.error} onRetry={refresh}/>:groups.loading&&!groups.data?<Loading/>:<>
            <Dropdown className="notification-group-dropdown" aria-label="选择通知群聊" placeholder="选择通知群聊" inlinePopup multiselect selectedOptions={selected} value={selectedGroups.length?`已选择 ${selectedGroups.length} 个工作群`:''} onOptionSelect={(_,data)=>select(data.selectedOptions)} listbox={{className:'notification-group-options'}}>
              {items.map(group=><Option key={group.id} value={group.id} text={identity(group)} disabled={!selectable(group)}><span className="group-option-label"><strong>{group.label}</strong><small>{group.groupNumber?'群号 '+group.groupNumber:'群号待补录'}{group.available===false?' · 当前机器人未识别':!group.enabled?' · 已停用':''}</small></span></Option>)}
            </Dropdown>
            {!items.length&&<p className="group-empty-hint">暂无工作群。请将机器人加入工作群，在群内发送一条消息后刷新。</p>}
            <div className="group-picker-tools"><span>{enabled.length} 个可用工作群</span><Button appearance="subtle" icon={<PencilSimple/>} disabled={!items.length} onClick={()=>setManage(true)}>核对群资料</Button></div>
            {selectedGroups.length>0&&<div className="selected-group-tags" aria-label="已选通知群聊">{selectedGroups.map(group=><div key={group.id}><span>{identity(group)}</span><Button appearance="subtle" size="small" aria-label={`取消选择 ${group.label}`} icon={<X size={14}/>} onClick={()=>select(selected.filter(id=>id!==group.id))}/></div>)}</div>}
          </>}
        </section>
        <section className="panel notification-history" aria-label="发送记录"><div className="panel-title"><div><h2>发送记录</h2></div><Badge appearance="outline">最近 50 条</Badge></div>
          <div className="notification-history-scroll" tabIndex={0} role="region" aria-label="发送记录滚动区域">{history.error?<Retry error={history.error} onRetry={refresh}/>:history.loading&&!history.data?<Loading/>:history.data?.items.length?<div className="notification-history-list">{history.data.items.map(item=><NotificationItem key={item.id} item={item} onEdit={()=>editAgain(item)} onDelete={()=>{setDeleteError('');setDeleting(item);}}/>)}</div>:<Empty title="还没有发送记录" description="发送后将在这里记录排队、成功或失败状态。"/>}</div>
          {permissionError&&<div className="notification-permission-help"><p>出现 40034105 时，请群主在手机 QQ 的该群机器人设置中开启“机器人主动在群聊内发言”。</p><a href="https://github.com/AstrBotDevs/AstrBot/wiki/zh-platform-qqofficial-webhook#设置机器人可获取的群聊消息范围和主动发言" target="_blank" rel="noreferrer">查看群主授权步骤</a></div>}
        </section>
      </div>
    </div>
    <Dialog open={!!deleting} onOpenChange={(_,data)=>{if(!data.open&&!deleteBusy)setDeleting(null);}}><DialogSurface className="delete-notification-dialog"><DialogBody><DialogTitle>删除发送记录</DialogTitle><DialogContent><p>确认删除「{deleting?.title}」的发送记录？</p><p className="muted">删除后将从发送记录中移除，不会撤回 QQ 群中已发送的消息。</p>{deleteError&&<Notice>{deleteError}</Notice>}</DialogContent><DialogActions><Button disabled={deleteBusy} onClick={()=>setDeleting(null)}>取消</Button><Button appearance="primary" icon={deleteBusy?<Spinner size="tiny"/>:<Trash/>} disabled={deleteBusy} onClick={()=>void removeRecord()}>{deleteBusy?'正在删除':'确认删除'}</Button></DialogActions></DialogBody></DialogSurface></Dialog>
    <Dialog open={!!deletingGroup} onOpenChange={(_,data)=>{if(!data.open&&!groupDeleteBusy)setDeletingGroup(null);}}><DialogSurface><DialogBody><DialogTitle>删除群聊</DialogTitle><DialogContent><p>确认从通知列表删除「{deletingGroup?.label}」？</p>{groupDeleteError&&<Notice>{groupDeleteError}</Notice>}</DialogContent><DialogActions><Button disabled={groupDeleteBusy} onClick={()=>setDeletingGroup(null)}>取消</Button><Button appearance="primary" icon={groupDeleteBusy?<Spinner size="tiny"/>:<Trash/>} disabled={groupDeleteBusy} onClick={()=>void removeGroup()}>{groupDeleteBusy?'正在删除':'确认删除'}</Button></DialogActions></DialogBody></DialogSurface></Dialog>
    <Dialog open={manage} onOpenChange={(_,data)=>setManage(data.open)}><DialogSurface className="group-details-dialog"><DialogBody><DialogTitle action={<Button appearance="subtle" aria-label="关闭群资料" icon={<X/>} onClick={()=>setManage(false)}/>}>核对群资料</DialogTitle><DialogContent>{items.map(group=><GroupEditor key={group.id} group={group} onSaved={refresh} onDelete={()=>{setGroupDeleteError('');setDeletingGroup(group);}}/>)}</DialogContent></DialogBody></DialogSurface></Dialog>
  </div>;
}
function GroupEditor({group,onSaved,onDelete}:{group:QqGroup;onSaved:()=>void;onDelete:()=>void}){
  const [label,setLabel]=useState(group.label),[number,setNumber]=useState(group.groupNumber||''),[enabled,setEnabled]=useState(group.enabled),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
  useEffect(()=>{setLabel(group.label);setNumber(group.groupNumber||'');setEnabled(group.enabled);},[group.label,group.groupNumber,group.enabled]);
  async function save(event:React.FormEvent){event.preventDefault();setBusy(true);setMessage('');try{await api(`/admin/qq/groups/${group.id}`,{method:'PATCH',body:{label,groupNumber:number,enabled}});setMessage('群资料已保存');onSaved();}catch(error){setMessage(messageOf(error));}finally{setBusy(false);}}
  return <form className="group-details-form" onSubmit={save} aria-label={`${group.label}的群资料`}><div className="group-details-heading"><strong>{group.label}</strong><Badge appearance="tint" color={group.available?'success':'subtle'}>{group.available?'当前机器人':'待当前机器人识别'}</Badge></div><Field label="群聊名称"><Input aria-label={`${group.label} 群聊名称`} value={label} maxLength={100} readOnly={group.nameSynced} required onChange={(_,data)=>setLabel(data.value)}/></Field><Field label="QQ 群号"><Input aria-label={`${group.label} QQ 群号`} inputMode="numeric" value={number} maxLength={15} pattern="[1-9][0-9]{4,14}" placeholder="填写真实数字群号" onChange={(_,data)=>setNumber(data.value.replace(/\D/g,''))}/></Field><div className="group-details-actions"><Checkbox checked={enabled} onChange={(_,data)=>setEnabled(data.checked===true)} label="启用通知"/><span/><Button type="button" appearance="subtle" icon={<Trash/>} onClick={onDelete}>删除群聊</Button><Button type="submit" appearance="primary" icon={busy?<Spinner size="tiny"/>:<Check/>} disabled={busy||!label.trim()}>保存群资料</Button></div><small role="status">{message}</small></form>;
}

async function copyNotice(text:string){
  try{await navigator.clipboard.writeText(text);return;}catch{/* Fall back for desktop clipboard permission differences. */}
  const area=document.createElement('textarea');area.value=text;area.style.cssText='position:fixed;left:-10000px;top:0';document.body.append(area);area.select();try{if(!document.execCommand('copy'))throw new Error('复制失败，请手动选择通知正文复制。');}finally{area.remove();}
}
function NotificationItem({item,onEdit,onDelete}:{item:NotificationRecord;onEdit:()=>void;onDelete:()=>void}){
  const [copyState,setCopyState]=useState('');
  async function copy(){try{await copyNotice('@全体成员\n【'+item.title+'】\n'+item.content);setCopyState('通知已复制');}catch{setCopyState('复制失败，请手动选择正文复制');}}
  const done=item.pendingCount===0,intent=item.failedCount?'danger':done?'success':'warning';return <article className="notification-item"><div className="notification-item-heading"><div><strong>{item.title}</strong><span>{dateTime(item.createdAt)} · {item.targetCount} 个群聊</span></div><Badge appearance="tint" color={intent}>{done?(item.failedCount?item.failedCount+' 个失败':'全部已发送'):item.pendingCount+' 个发送中'}</Badge></div><p>{item.content}</p>{item.attachments?.length>0&&<div className="notification-record-attachments">{item.attachments.map(attachment=><span key={attachment.id}><Paperclip/>{attachment.name}</span>)}</div>}<div className="notification-targets">{item.targets.map(target=><span key={target.id} title={target.lastError?.includes('40034105')?'请群主开启该群机器人的主动发言权限':target.lastError||undefined} className={'target-state '+target.status}><span className="tiny-dot"/>{target.groupLabel} · {target.status==='sent'?'已发送':target.status==='failed'?(target.lastError?.includes('40034105')?'主动发言未授权（40034105）':target.lastError||'发送失败'):target.status==='processing'?'正在发送':'排队中'}</span>)}</div><div className="notification-record-actions"><Button appearance="subtle" icon={<Copy/>} onClick={()=>void copy()}>复制通知</Button>{item.failedCount>0&&<Button appearance="subtle" icon={<NotePencil/>} onClick={onEdit}>重新编辑</Button>}<Button appearance="subtle" icon={<Trash/>} disabled={!done} title={done?'删除这条发送记录':'发送结束后可删除记录'} onClick={onDelete}>删除记录</Button><small role="status">{copyState|| (item.targets.some(target=>!!target.messageId)?'QQ 已确认接收':'' )}</small></div></article>;
}
